class Appu{
	public static void main(String[] args){
		String movieName= "Appu";
		System.out.println(movieName);
		movieName= "Abhi";
		System.out.println(movieName);
		movieName= "Veera Kannadiga";
		System.out.println(movieName);
		movieName= "Maurya";
		System.out.println(movieName);
		movieName= "Akash";
		System.out.println(movieName);
		movieName= "Namma Basava";
		System.out.println(movieName);
		movieName= "Ajay";
		System.out.println(movieName);
		movieName= "Milana";
		System.out.println(movieName);
		movieName= "Bindas";
		System.out.println(movieName);
		movieName= "Arasu";
		System.out.println(movieName);
		movieName= "Vamshi";
		System.out.println(movieName);
		movieName= "Raam";
		System.out.println(movieName);
		movieName= "Raj";
		System.out.println(movieName);
		movieName= "Pruthvi";
		System.out.println(movieName);
		movieName= "Jackie";
		System.out.println(movieName);
		movieName= "Huduguru";
		System.out.println(movieName);
		movieName= "Paramathma";
		System.out.println(movieName);
		movieName= "Annabond";
		System.out.println(movieName);
		movieName= "Yare Kughadali";
		System.out.println(movieName);
		movieName= "Ninnindale";
		System.out.println(movieName);
		movieName= "Power";
		System.out.println(movieName);
		movieName= "Mythri";
		System.out.println(movieName);
		movieName= "Rana Vikrama";
		System.out.println(movieName);
		movieName= "Chakravyuha";
		System.out.println(movieName);
		movieName= "Doddamane Hudga";
		System.out.println(movieName);
		movieName= "Anjani Putra";
		System.out.println(movieName);
		movieName= "RajaKumara";
		System.out.println(movieName);
		movieName= "Natasarvabhowma";
		System.out.println(movieName);
		movieName= "Yuvarathna";
		System.out.println(movieName);
		movieName= "James";
		System.out.println(movieName);
		movieName= "Gandhada Gudi";
		System.out.println(movieName);
	}
}