class Artists{
	public static void main(String[] args)
	{
		String artistName= "1.Raja Ravi Varma";
		System.out.println(artistName);
		artistName= "2.Amrita Sher-Gil";
		System.out.println(artistName);
		artistName= "3.Abanindranath";
		System.out.println(artistName);
		artistName= "4.Rabhindranath Tagore";
		System.out.println(artistName);
		artistName= "5.Nandal Bose";
		System.out.println(artistName);
		artistName= "6.Jamini Roy";
		System.out.println(artistName);
		artistName= "7.Ganganendranath Tagore";
		System.out.println(artistName);
		artistName= "8.Ramkinkar Behari Mukherjee";
		System.out.println(artistName);
		artistName= "9.Benode Behari Mukherjee";
		System.out.println(artistName);
		artistName= "10.Mukhul Dey";
		System.out.println(artistName);
		artistName= "11.M.F.Husain";
		System.out.println(artistName);
		artistName= "12.S.H.Raza";
		System.out.println(artistName);
		artistName= "3.F.N.souza";
		System.out.println(artistName);
		artistName= "14.V.S.Gaitonda";
		System.out.println(artistName);
		artistName= "15.Tyeb Mehta";
		System.out.println(artistName);
		artistName= "16.Akbar Padmsee";
		System.out.println(artistName);
		artistName= "17.Ram Kumar";
		System.out.println(artistName);
		artistName= "18.Krishen Khanna";
		System.out.println(artistName);
		artistName= "19.K.H.Ara";
		System.out.println(artistName);
		artistName= "20.Sadanand Bakre";
		System.out.println(artistName);
		artistName= "21.Satish Gujral";
		System.out.println(artistName);
		artistName= "22.K.G.Subramanyam";
		System.out.println(artistName);
		artistName= "23.Bhuoen Khakhar";
		System.out.println(artistName);
		artistName= "24.Manjith Bewa";
		System.out.println(artistName);
		artistName= "25.jogen Chowdhury";
		System.out.println(artistName);
		artistName= "26.Ganesh Pyne";
		System.out.println(artistName);
		artistName= "27.Bikash Bhattacharjee";
		System.out.println(artistName);
		artistName= "28.Arpitha Singh";
		System.out.println(artistName);
		artistName= "29.Anjoliee Ela Menon";
		System.out.println(artistName);
		artistName= "30.A.Ramachandran";
		System.out.println(artistName);
		artistName= "31.Gulam Mohammed Sheikh";
		System.out.println(artistName);
		artistName= "32.Rameshwar Broota";
		System.out.println(artistName);
		artistName= "33.Laxma Goud";
		System.out.println(artistName);
		artistName= "34.Thota Vaikuntum";
		System.out.println(artistName);
		artistName= "35.Nasreen Mohamedi";
		System.out.println(artistName);
		artistName= "36.Zarina Hashmi";
		System.out.println(artistName);
		artistName= "37.Anish Kapoor";
		System.out.println(artistName);
		artistName= "38.Subodh Gupta";
		System.out.println(artistName);
		artistName= "39.Bharti Kher";
		System.out.println(artistName);
		artistName= "40.Atul Dodiya";
		System.out.println(artistName);
		artistName= "41.Jitish Kallat";
		System.out.println(artistName);
		artistName= "42.Reena Saini Kallat";
		System.out.println(artistName);
		artistName= "43.Nalini Malani";
		System.out.println(artistName);
		artistName= "44.Vivan Sudaram";
		System.out.println(artistName);
		artistName= "45.Sudhir Patwardhan";
		System.out.println(artistName);
		artistName= "46.Paresh Maity";
		System.out.println(artistName);
		artistName= "47.Shilpa Gupta";
		System.out.println(artistName);
		artistName= "48.Raqib Shaw";
		System.out.println(artistName);
		artistName= "49.Ravinder Reddy";
		System.out.println(artistName);
		artistName= "50.N.S.Harsha";
		System.out.println(artistName);	
	}
}