class CarCompanies{
	public static void main(String[] args){
		String carCompany= "1.Maruthi Suxuki";
		System.out.println(carCompany);
		carCompany= "2.Hynudai";
		System.out.println(carCompany);
		carCompany= "3.Tata Motors";
		System.out.println(carCompany);
		carCompany= "4.Mahindra";
		System.out.println(carCompany);
		carCompany= "5.Kia";
		System.out.println(carCompany);
		carCompany= "6.Toyota";
		System.out.println(carCompany);
		carCompany= "7.Honda";
		System.out.println(carCompany);
		carCompany= "8.MG Motor";
		System.out.println(carCompany);
		carCompany= "9.Renault";
		System.out.println(carCompany);
		carCompany= "10.Volkswagen";
		System.out.println(carCompany);
		carCompany= "11.Skoda";
		System.out.println(carCompany);
		carCompany= "12.Citroen";
		System.out.println(carCompany);
		carCompany= "13.Jeep";
		System.out.println(carCompany);
		carCompany= "14.Lsuzu";
		System.out.println(carCompany);
		carCompany= "15.BYD";
		System.out.println(carCompany);
		carCompany= "16.Pravaig";
		System.out.println(carCompany);
		carCompany= "17.Mecredes-Benz";
		System.out.println(carCompany);
		carCompany= "18.BMW";
		System.out.println(carCompany);
		carCompany= "19.Audi";
		System.out.println(carCompany);
		carCompany= "20.Jaguar Land Rover";
		System.out.println(carCompany);
		carCompany= "21.Vovlo";
		System.out.println(carCompany);
		carCompany= "22.Lexus";
		System.out.println(carCompany);
		carCompany= "23.Mini";
		System.out.println(carCompany);
		carCompany= "24.Porsche";
		System.out.println(carCompany);
		carCompany= "25.Ferrari";
		System.out.println(carCompany);
		carCompany= "26.Lamboghini";
		System.out.println(carCompany);
		carCompany= "27.Rools-Royce";
		System.out.println(carCompany);
		carCompany= "28.Bentley";
		System.out.println(carCompany);
		carCompany= "29.Maserati";
		System.out.println(carCompany);
		carCompany= "30.Aston Martin";
		System.out.println(carCompany);
		carCompany= "31.McLaren";
		System.out.println(carCompany);
	}
}