class Dances{
	public static void main(String [] args){
		String dance= "Bharathanatyam";
		System.out.println(dance);
		dance= "kathak";
		System.out.println(dance);
		dance= "Kuchipudi";
		System.out.println(dance);
		dance= "Kathak";
		System.out.println(dance);
		dance= "Odissi";
		System.out.println(dance);
		dance= "Manipuri";
		System.out.println(dance);
		dance= "Mohiniyattam";
		System.out.println(dance);
		dance= "Sattriya";
		System.out.println(dance);
		dance= "Bhangra";
		System.out.println(dance);
		dance= "Giddha";
		System.out.println(dance);
		dance= "Jhumar";
		System.out.println(dance);
		dance= "Chholiya";
		System.out.println(dance);
		dance= "Garba";
		System.out.println(dance);
		dance= "Dandiya Rass";
		System.out.println(dance);
		dance= "Ghoomar";
		System.out.println(dance);
		dance= "Kalbelia";
		System.out.println(dance);
		dance= "Bhavai";
		System.out.println(dance);
		dance= "Lavani";
		System.out.println(dance);
		dance= "Bihu";
		System.out.println(dance);
		dance= "Chhau";
		System.out.println(dance);
		dance= "Gotipua";
		System.out.println(dance);
		dance= "Sambalpuri";
		System.out.println(dance);
		dance= "Yakshagana";
		System.out.println(dance);
		dance= "Dollu Kunitha";
		System.out.println(dance);
		dance= "Kummi";
		System.out.println(dance);
		dance= "Kolattam";
		System.out.println(dance);
		dance= "Karagattam";
		System.out.println(dance);
		dance= "Theyyam";
		System.out.println(dance);
		dance= "Thirayattam";
		System.out.println(dance);
		dance= "Santhali Dance";
		System.out.println(dance);
		dance= "Hojagiri";
		System.out.println(dance);
		dance= "Cheraw";
		System.out.println(dance);
		dance= "Bison Horn Dance";
		System.out.println(dance);
		dance= "Wangala Dance";
		System.out.println(dance);
		dance= "Rouf";
		System.out.println(dance);
		dance= "Dalkhai";
		System.out.println(dance);
		dance= "Perini Shivatandavam";
		System.out.println(dance);
		dance= "Veeragase";
		System.out.println(dance);
		dance= "Singhi Chham";
		System.out.println(dance);
		dance= "Mask Dance";
		System.out.println(dance);
	}
}