class Vegitables{
	public static void main(String[] args){
		String vegitable= "1.Carrot";
		System.out.println(vegitable);
		vegitable= "2.Patato";
		System.out.println(vegitable);
		vegitable= "3.Sweet Patato";
		System.out.println(vegitable);
		vegitable= "4.Yam";
		System.out.println(vegitable);
		vegitable= "5.Beetroot";
		System.out.println(vegitable);
		vegitable= "6.Radish";
		System.out.println(vegitable);
		vegitable= "7.Daikon Raish";
		System.out.println(vegitable);
		vegitable= "8.Turnip";
		System.out.println(vegitable);
		vegitable= "9.Rutabaga";
		System.out.println(vegitable);
		vegitable= "10.Onion";
		System.out.println(vegitable);
		vegitable="11.Beans";
		System.out.println(vegitable);
		vegitable="12.LadiesFinger";
		System.out.println(vegitable);
		vegitable="13.Cucumber";
		System.out.println(vegitable);
		vegitable= "14.Chilly";
		System.out.println(vegitable);
		vegitable="15.DrumStick";
		System.out.println(vegitable);
		vegitable="16.Lemon";
		System.out.println(vegitable);
		vegitable="17.Parsnip";
		System.out.println(vegitable);
		vegitable= "18.Celeriac";
		System.out.println(vegitable);
		vegitable= "19.Taro";
		System.out.println(vegitable);
		vegitable= "20.Jicama";
		System.out.println(vegitable);
		vegitable= "21.Kohrabi";
		System.out.println(vegitable);
		vegitable= "22.Ginger";
		System.out.println(vegitable);
		vegitable= "23.Green Beans";
		System.out.println(vegitable);
		vegitable= "24.French Beans";
		System.out.println(vegitable);
		vegitable= "25.Snow Beans";
		System.out.println(vegitable);
		vegitable= "26.Sugar Snap Peas";
		System.out.println(vegitable);
		vegitable= "27.Garden Peas";
		System.out.println(vegitable);
		vegitable= "28.Radish";
		System.out.println(vegitable);
		vegitable= "29.Daikon Raish";
		System.out.println(vegitable);
		vegitable= "30.Turnip";
		System.out.println(vegitable);
		vegitable= "31.Rutabaga";
		System.out.println(vegitable);
		vegitable= "31.Onion";
		System.out.println(vegitable);
		vegitable="32.Beans";
		System.out.println(vegitable);
		vegitable="33.LadiesFinger";
		System.out.println(vegitable);
		vegitable="34.Cucumber";
		System.out.println(vegitable);
		vegitable= "35.Chilly";
		System.out.println(vegitable);
		vegitable="36.DrumStick";
		System.out.println(vegitable);
		vegitable="37.Lemon";
		System.out.println(vegitable);
		vegitable="38.Parsnip";
		System.out.println(vegitable);
		vegitable= "39.Celeriac";
		System.out.println(vegitable);
		vegitable= "41.Taro";
		System.out.println(vegitable);
		vegitable= "42.Jicama";
		System.out.println(vegitable);
		vegitable= "43.Kohrabi";
		System.out.println(vegitable);
		vegitable= "44.Ginger";
		System.out.println(vegitable);
		vegitable= "45.Tumeric";
		System.out.println(vegitable);
		vegitable= "46.Galangal";
		System.out.println(vegitable);
		vegitable= "47.Lotus Root";
		System.out.println(vegitable);
		vegitable= "48.Burdock Root";
		System.out.println(vegitable);
		vegitable= "49.Salsify";
		System.out.println(vegitable);
		vegitable= "50.Wasabi";
		System.out.println(vegitable);
		vegitable= "51.Arrowroot";
		System.out.println(vegitable);
		vegitable= "52.Water Chestnut";
		System.out.println(vegitable);
		vegitable= "53.Tomato";
		System.out.println(vegitable);
		vegitable= "54.Cherru Tomato";
		System.out.println(vegitable);
		vegitable="55.Zucchini";
		System.out.println(vegitable);
		vegitable="56.Yellow Squash";
		System.out.println(vegitable);
		vegitable="57.EggPlant";
		System.out.println(vegitable);
		vegitable= "58.Broad Beans";
		System.out.println(vegitable);
		vegitable="59.Lima Beans";
		System.out.println(vegitable);
		vegitable="60.Lentils";
		System.out.println(vegitable);
		vegitable="61.Kidney Beans";
		System.out.println(vegitable);
		vegitable= "62.Blck-Eye Peas";
		System.out.println(vegitable);
		vegitable= "63.Cluster Beans";
		System.out.println(vegitable);
		vegitable= "64.Winged Beans";
		System.out.println(vegitable);
		vegitable= "65.Yardlong Beans";
		System.out.println(vegitable);
		vegitable= "66.Shallot";
		System.out.println(vegitable);
		vegitable= "67.Chives";
		System.out.println(vegitable);
		vegitable= "68.MushroomButton";
		System.out.println(vegitable);
		vegitable= "69.PortobelloMushroom";
		System.out.println(vegitable);
		vegitable="70.Spinach";
		System.out.println(vegitable);
		vegitable= "71.Kale";
		System.out.println(vegitable);
		vegitable="72.Romaine Lettuce";
		System.out.println(vegitable);
		vegitable= "73.Pumpkin";
		System.out.println(vegitable);
		vegitable= "74.Butternut";
		System.out.println(vegitable);
		vegitable= "75.GreenBellPepper";
		System.out.println(vegitable);
		vegitable= "76.RedBellPepper";
		System.out.println(vegitable);
		vegitable="77.YellowBellPepper";
		System.out.println(vegitable);
		vegitable="78.OrangePepper";
		System.out.println(vegitable);
		vegitable="79.SnakeGourd";
		System.out.println(vegitable);
		vegitable="80.Ivy Gourd";
		System.out.println(vegitable);
		vegitable="81.Ridge Gourd";
		System.out.println(vegitable);
		vegitable="82.Pointed Gourd";
		System.out.println(vegitable);
		vegitable="83.Parsnip";
		System.out.println(vegitable);
		vegitable= "84.AshGroud";
		System.out.println(vegitable);
		vegitable= "85.Okra";
		System.out.println(vegitable);
		vegitable= "86.Chayote";
		System.out.println(vegitable);
		vegitable= "87.Tomatillo";
		System.out.println(vegitable);
		vegitable= "88.Jalapeno";
		System.out.println(vegitable);
		vegitable= "89.BokChoy";
		System.out.println(vegitable);
		vegitable= "90.Endive";
		System.out.println(vegitable);
		vegitable= "91.Arugula";
		System.out.println(vegitable);
		vegitable= "92.Spring Onion";
		System.out.println(vegitable);
		vegitable= "93.Leek";
		System.out.println(vegitable);
		vegitable= "94.Fennel";
		System.out.println(vegitable);
		vegitable= "95.Sorrel";
		System.out.println(vegitable);
		vegitable= "96.Beet Greens";
		System.out.println(vegitable);
		vegitable= "97.Amaranath Leaves";
		System.out.println(vegitable);
		vegitable= "98.Fenugreek Leaves";
		System.out.println(vegitable);
		vegitable= "99.Corn";
		System.out.println(vegitable);
		vegitable= "100.Asparagus";
		System.out.println(vegitable);
		
		
	}
		
}