class ProductRunner{
	public static void main(String[] args){
		Product product =new Product("T-Shirt","","12-02-2024",500,ProductType.CLOTHES,"Krushnamurthy",ProductWarrentyYear.ONE,false,1001,"India");
		Product product1 =new Product("Shirt","","13-02-2024",500,ProductType.CLOTHES,"Narayan",ProductWarrentyYear.ONE,false,1002,"china");
		Product product2 =new Product("Books","","12-02-2024",500,ProductType.STUDY_MATIREAL,"Sharath",ProductWarrentyYear.ONE,false,10,"India");
		Product product3 =new Product("Santoor","","11-02-2024",40,ProductType.SOAP,"Trivedha",ProductWarrentyYear.ONE,false,11,"India");
		Product product4 =new Product("Titan Watch","","12-02-2024",2000,ProductType.WATCH,"Guru",ProductWarrentyYear.ONE,false,1003,"India");
		Product product5 =new Product("Pant","","12-12-2025",500,ProductType.CLOTHES,"Krushnamurthy",ProductWarrentyYear.ONE,false,1,"India");
		Product product6 =new Product("Shirt","","23-02-2024",500,ProductType.CLOTHES,"Krushnamurthy",ProductWarrentyYear.ONE,false,2,"India");
		Product product7 =new Product("Bagi Pant","","10-02-2024",1500,ProductType.CLOTHES,"Krushnamurthy",ProductWarrentyYear.ONE,false,3,"India");
		Product product8 =new Product("Half Shirt","","12-12-2024",500,ProductType.CLOTHES,"Krushnamurthy",ProductWarrentyYear.ONE,false,3,"India");
		Product product9 =new Product("Dress","","12-09-2024",5100,ProductType.CLOTHES,"Krushnamurthy",ProductWarrentyYear.ONE,false,4,"India");
		Product product10 =new Product("Sarry","","19-02-2024",500,ProductType.CLOTHES,"Krushnamurthy",ProductWarrentyYear.ONE,false,11,"India");
		Product product11 =new Product("Kurtha","","15-02-2024",2000,ProductType.CLOTHES,"Krushnamurthy",ProductWarrentyYear.ONE,false,10,"India");
		Product product12 =new Product("Couat","","11-02-2024",5000,ProductType.CLOTHES,"Krushnamurthy",ProductWarrentyYear.ONE,false,14,"India");
		Product product13 =new Product("Baniyan","","12-02-2023",500,ProductType.CLOTHES,"Krushnamurthy",ProductWarrentyYear.ONE,false,12,"India");
		Product product14 =new Product("Lowers","","12-06-2024",500,ProductType.CLOTHES,"Krushnamurthy",ProductWarrentyYear.ONE,false,14,"India");
		Product product15 =new Product("Track pants","","14-02-2024",1000,ProductType.CLOTHES,"Krushnamurthy",ProductWarrentyYear.ONE,false,23,"India");
		Product product16 =new Product("Book","","15-02-2024",100,ProductType.STUDY_MATIREAL,"Suresh",ProductWarrentyYear.ZERO,false,10,"India");
		Product product17=new Product("Pen","","14-02-2026",10,ProductType.STUDY_MATIREAL,"Suresh",ProductWarrentyYear.ZERO,false,11,"India");
		Product product18 =new Product("Pencil","","12-02-2024",10,ProductType.STUDY_MATIREAL,"Suresh",ProductWarrentyYear.ZERO,false,12,"India");
		Product product19=new Product("Notes","","11-08-2024",200,ProductType.STUDY_MATIREAL,"Suresh",ProductWarrentyYear.ZERO,false,13,"India");
		Product product20 =new Product("Sharpner","","14-02-2024",10,ProductType.STUDY_MATIREAL,"Suresh",ProductWarrentyYear.ZERO,false,15,"India");
		Product product21 =new Product("Drawing Book","","14-02-2024",100,ProductType.STUDY_MATIREAL,"Suresh",ProductWarrentyYear.ZERO,false,15,"India");
		Product product22 =new Product("Color pens","","14-02-2024",100,ProductType.STUDY_MATIREAL,"Suresh",ProductWarrentyYear.ZERO,false,16,"India");
		Product product23 =new Product("A4 Sheets","","14-02-2024",10,ProductType.STUDY_MATIREAL,"Suresh",ProductWarrentyYear.ZERO,false,17,"India");
		Product product24 =new Product("Exam Sheets","","14-02-2024",10,ProductType.STUDY_MATIREAL,"Suresh",ProductWarrentyYear.ZERO,false,18,"India");
		Product product25 =new Product("Scale","","14-02-2024",10,ProductType.STUDY_MATIREAL,"Suresh",ProductWarrentyYear.ZERO,false,19,"India");
		Product product26 =new Product("Compus","","14-02-2024",100,ProductType.STUDY_MATIREAL,"Suresh",ProductWarrentyYear.ZERO,false,32,"India");
		Product product27 =new Product("Science Book","","19-02-2024",1000,ProductType.STUDY_MATIREAL,"Suresh",ProductWarrentyYear.ZERO,false,21,"India");
		Product product28 =new Product("Java Core Book","","24-05-2024",3000,ProductType.STUDY_MATIREAL,"Suresh",ProductWarrentyYear.ZERO,false,14,"India");
		Product product29 =new Product("Frontend Book","","24-02-2024",1000,ProductType.STUDY_MATIREAL,"Suresh",ProductWarrentyYear.ZERO,false,10,"India");
		Product product30 =new Product("Java Backend","","13-02-2024",1000,ProductType.STUDY_MATIREAL,"Suresh",ProductWarrentyYear.ZERO,false,21,"India");
		Product product31 =new Product("JavaScript","","14-02-2021",1000,ProductType.STUDY_MATIREAL,"Suresh",ProductWarrentyYear.ZERO,false,41,"India");
		Product product51 =new Product("System Testing","","14-02-2002",1000,ProductType.STUDY_MATIREAL,"Suresh",ProductWarrentyYear.ZERO,false,38,"India");
		Product product32 =new Product("BhagvathGitha","","14-02-1983",1000,ProductType.STUDY_MATIREAL,"Suresh",ProductWarrentyYear.ZERO,false,47,"India");
		Product product33 =new Product("Python","","14-02-2012",1000,ProductType.STUDY_MATIREAL,"Suresh",ProductWarrentyYear.ZERO,false,51,"India");
		Product product34 =new Product("C++","","14-02-2015",1000,ProductType.STUDY_MATIREAL,"Suresh",ProductWarrentyYear.ZERO,false,52,"India");
		Product product35 =new Product("Machine Learning","","14-02-2017",1000,ProductType.STUDY_MATIREAL,"Suresh",ProductWarrentyYear.ZERO,false,53,"India");
		Product product36 =new Product("Crytography","","14-02-2017",1000,ProductType.STUDY_MATIREAL,"Suresh",ProductWarrentyYear.ZERO,false,54,"India");
		Product product37 =new Product("Quantum Physics","","14-02-2018",1000,ProductType.STUDY_MATIREAL,"Suresh",ProductWarrentyYear.ZERO,false,55,"India");
		Product product38 =new Product("Maths","","14-02-2020",1000,ProductType.STUDY_MATIREAL,"Suresh",ProductWarrentyYear.ZERO,false,56,"India");
		Product product39 =new Product("DataBase","","14-06-2024",1000,ProductType.STUDY_MATIREAL,"Suresh",ProductWarrentyYear.ZERO,false,57,"India");
		Product product40 =new Product("MicroController","","15-02-2024",1000,ProductType.STUDY_MATIREAL,"Suresh",ProductWarrentyYear.ZERO,false,58,"India");
		Product product41= new Product("Lux","","15-08-2018",50,ProductType.SOAP,"Shahir",ProductWarrentyYear.ONE,false,1,"India");
		Product product42= new Product("Li-bi","","17-08-2018",50,ProductType.SOAP,"Shahir",ProductWarrentyYear.ONE,true,2,"India");
		Product product43= new Product("Mysore Sandal","","12-08-2018",150,ProductType.SOAP,"Shahir",ProductWarrentyYear.ONE,false,3,"India");
		Product product44= new Product("Medimix","","12-07-2018",30,ProductType.SOAP,"Shahir",ProductWarrentyYear.ONE,true,4,"India");
		Product product45= new Product("Ghar Soap","","12-09-2018",500,ProductType.SOAP,"Shahir",ProductWarrentyYear.ONE,false,5,"India");
		Product product46= new Product("Cithol","","12-02-2019",80,ProductType.SOAP,"Shahir",ProductWarrentyYear.ONE,false,6,"India");
		Product product47= new Product("Detol","","18-08-2018",60,ProductType.SOAP,"Shahir",ProductWarrentyYear.ONE,false,7,"India");
		Product product48= new Product("Baby","","22-08-2018",80,ProductType.SOAP,"Shahir",ProductWarrentyYear.ONE,false,8,"India");
		Product product49= new Product("Lemon Santoor","","12-08-2018",50,ProductType.SOAP,"Shahir",ProductWarrentyYear.ONE,false,9,"India");
		Product product50= new Product("Pink Lux","","12-08-2018",50,ProductType.SOAP,"Shahir",ProductWarrentyYear.ONE,false,10,"India");
		Product product52 =new Product("Night Pants","","18-08-2023",500,ProductType.CLOTHES,"Rajesh",ProductWarrentyYear.ONE,false,108,"India");
		Product product53 =new Product("Kur Kure","","12-02-2024",50,ProductType.SNAKS,"Gagan",ProductWarrentyYear.TWO,true,17,"India");
		Product product54 =new Product("chips","","12-07-2024",50,ProductType.SNAKS,"Gagan",ProductWarrentyYear.TWO,true,16,"India");
		Product product55 =new Product("maryGold Biscuit","","12-05-2024",50,ProductType.SNAKS,"Gagan",ProductWarrentyYear.TWO,true,15,"India");
		Product product56 =new Product("Gooday Biscuit","","11-02-2024",40,ProductType.SNAKS,"Gagan",ProductWarrentyYear.TWO,true,14,"India");
		Product product57 =new Product("Cream Bisuit","","15-02-2024",30,ProductType.SNAKS,"Gagan",ProductWarrentyYear.TWO,true,13,"India");
		Product product58 =new Product("banana Chips","","14-02-2024",20,ProductType.SNAKS,"Gagan",ProductWarrentyYear.TWO,true,12,"India");
		Product product59 =new Product("Magi","","12-02-2022",50,ProductType.SNAKS,"Gagan",ProductWarrentyYear.TWO,true,11,"India");
		Product product60 =new Product("Dairy Milk","","12-02-2014",70,ProductType.SNAKS,"Gagan",ProductWarrentyYear.TWO,true,10,"India");
		Product product61 =new Product("Tedy-Medy","","12-02-2024",50,ProductType.SNAKS,"Gagan",ProductWarrentyYear.TWO,true,1,"India");
		Product product62 =new Product("Karachi ","","12-02-2024",70,ProductType.SNAKS,"Gagan",ProductWarrentyYear.TWO,true,2,"India");
		Product product63 =new Product("Mitayi","","12-02-2025",80,ProductType.SNAKS,"Gagan",ProductWarrentyYear.TWO,true,3,"India");
		Product product64 =new Product("Milki Bar","","12-07-2024",500,ProductType.SNAKS,"Gagan",ProductWarrentyYear.TWO,true,4,"India");
		Product product65 =new Product("Gobhi","","12-06-2024",30,ProductType.SNAKS,"Gagan",ProductWarrentyYear.TWO,true,5,"India");
		Product product66 =new Product("Pizza","","22-02-2024",50,ProductType.SNAKS,"Gagan",ProductWarrentyYear.TWO,true,6,"India");
		Product product67 =new Product("Burgar","","22-02-2024",60,ProductType.SNAKS,"Gagan",ProductWarrentyYear.TWO,true,7,"India");
		Product product68 =new Product("Cake","","13-02-2024",80,ProductType.SNAKS,"Gagan",ProductWarrentyYear.TWO,true,8,"India");
		Product product69 =new Product("FrenchPrice","","12-02-2024",50,ProductType.SNAKS,"Gagan",ProductWarrentyYear.TWO,true,1,"India");
		Product product70 =new Product("Egg","","12-06-2024",500,ProductType.SNAKS,"Gagan",ProductWarrentyYear.TWO,true,9,"India");
		Product product71 =new Product("Ring Chips","","13-02-2024",90,ProductType.SNAKS,"Gagan",ProductWarrentyYear.TWO,true,110,"India");
		Product product72 =new Product("bitroot","","12-02-2024",50,ProductType.VEGITABLES,"GovinaSwami",ProductWarrentyYear.ONE,false,109,"India");
		Product product73 =new Product("LadiesFinger","","null",50,ProductType.VEGITABLES,"GovinaSwami",ProductWarrentyYear.ZERO,false,108,"India");
		Product product74 =new Product("Patato","","null",60,ProductType.VEGITABLES,"GovinaSwami",ProductWarrentyYear.ZERO,false,101,"India");
		Product product75 =new Product("Onion","","null",70,ProductType.VEGITABLES,"GovinaSwami",ProductWarrentyYear.ZERO,false,102,"India");
		Product product76 =new Product("Chilli","","null",80,ProductType.VEGITABLES,"GovinaSwami",ProductWarrentyYear.ZERO,false,103,"India");
		Product product77 =new Product("Tamoto","","null",30,ProductType.VEGITABLES,"GovinaSwami",ProductWarrentyYear.ZERO,false,104,"India");
		Product product78 =new Product("Moolangi","","null",50,ProductType.VEGITABLES,"GovinaSwami",ProductWarrentyYear.ZERO,false,105,"India");
		Product product79 =new Product("Carrot","","null",70,ProductType.VEGITABLES,"GovinaSwami",ProductWarrentyYear.ZERO,false,106,"India");
		Product product80 =new Product("Beens","","null",80,ProductType.VEGITABLES,"GovinaSwami",ProductWarrentyYear.ZERO,false,107,"India");
		Product product81 =new Product("Mango","","",100,ProductType.FRUITES,"Samruth",ProductWarrentyYear.ZERO,false,1,"India");
		Product product82 =new Product("Apple","","",100,ProductType.FRUITES,"Samruth",ProductWarrentyYear.ZERO,false,2,"India");
		Product product83 =new Product("Banana","","",200,ProductType.FRUITES,"Samruth",ProductWarrentyYear.ZERO,false,3,"India");
		Product product84 =new Product("Sithapala","","",100,ProductType.FRUITES,"Samruth",ProductWarrentyYear.ZERO,false,4,"India");
		Product product85 =new Product("JackFruit","","",400,ProductType.FRUITES,"Samruth",ProductWarrentyYear.ZERO,false,5,"India");
		Product product86 =new Product("Promogranete","","",300,ProductType.FRUITES,"Samruth",ProductWarrentyYear.ZERO,false,6,"India");
		Product product87 =new Product("Sapoto","","",80,ProductType.FRUITES,"Samruth",ProductWarrentyYear.ZERO,false,7,"India");
		Product product88 =new Product("WaterMelon","","",100,ProductType.FRUITES,"Samruth",ProductWarrentyYear.ZERO,false,8,"India");
		Product product89 =new Product("Pinaple","","",100,ProductType.FRUITES,"Samruth",ProductWarrentyYear.ZERO,false,9,"India");
		Product product90=new Product("Masmelon","","",100,ProductType.FRUITES,"Samruth",ProductWarrentyYear.ZERO,false,0,"India");
		Product product91 =new Product("Moosambi","","",90,ProductType.FRUITES,"Samruth",ProductWarrentyYear.ZERO,false,11,"India");
		Product product92 =new Product("ClinicPlus","","12-02-2024",500,ProductType.SHAMPOO,"NiranjanMurthy",ProductWarrentyYear.ONE,false,102,"India");
		Product product93 =new Product("Detan","","12-02-2024",450,ProductType.SHAMPOO,"NiranjanMurthy",ProductWarrentyYear.ONE,false,103,"India");
		Product product94 =new Product("HeadandShoulder","","12-02-2024",500,ProductType.SHAMPOO,"NiranjanMurthy",ProductWarrentyYear.ONE,false,104,"India");
		Product product95 =new Product("Chik","","12-02-2024",90,ProductType.SHAMPOO,"NiranjanMurthy",ProductWarrentyYear.ONE,false,105,"India");
		Product product96 =new Product("Karthika","","12-02-2024",100,ProductType.SHAMPOO,"NiranjanMurthy",ProductWarrentyYear.ONE,false,106,"India");
		Product product97 =new Product("Sunsilk","","12-02-2024",100,ProductType.SHAMPOO,"NiranjanMurthy",ProductWarrentyYear.ONE,false,108,"India");
		Product product98 =new Product("Panteno","","12-02-2024",200,ProductType.SHAMPOO,"NiranjanMurthy",ProductWarrentyYear.ONE,false,109,"India");
		Product product99 =new Product("Cinthol","","12-02-2024",300,ProductType.SHAMPOO,"NiranjanMurthy",ProductWarrentyYear.ONE,false,110,"India");
		Product product100 =new Product("Modicare","","12-02-2024",500,ProductType.SHAMPOO,"NiranjanMurthy",ProductWarrentyYear.ONE,false,111,"India");
		Product product101 =new Product("T-Shirt","","12-02-2024",500,ProductType.CLOTHES,"Krushnamurthy",ProductWarrentyYear.ONE,false,1001,"India");
		Product product102 =new Product("T-Shirt","","12-02-2024",500,ProductType.CLOTHES,"Krushnamurthy",ProductWarrentyYear.ONE,false,1001,"India");
		Product product103 =new Product("T-Shirt","","12-02-2024",500,ProductType.CLOTHES,"Krushnamurthy",ProductWarrentyYear.ONE,false,1001,"India");
		Product product104 =new Product("T-Shirt","","12-02-2024",500,ProductType.CLOTHES,"Krushnamurthy",ProductWarrentyYear.ONE,false,1001,"India");
		Product product105 =new Product("T-Shirt","","12-02-2024",500,ProductType.CLOTHES,"Krushnamurthy",ProductWarrentyYear.ONE,false,1001,"India");
		Product product106 =new Product("T-Shirt","","12-02-2024",500,ProductType.CLOTHES,"Krushnamurthy",ProductWarrentyYear.ONE,false,1001,"India");
		Product product107 =new Product("T-Shirt","","12-02-2024",500,ProductType.CLOTHES,"Krushnamurthy",ProductWarrentyYear.ONE,false,1001,"India");
		Product product108 =new Product("T-Shirt","","12-02-2024",500,ProductType.CLOTHES,"Krushnamurthy",ProductWarrentyYear.ONE,false,1001,"India");
		Product product109 =new Product("T-Shirt","","12-02-2024",500,ProductType.CLOTHES,"Krushnamurthy",ProductWarrentyYear.ONE,false,1001,"India");
		Product product110 =new Product("T-Shirt","","12-02-2024",500,ProductType.CLOTHES,"Krushnamurthy",ProductWarrentyYear.ONE,false,1001,"India");
		Product product111 =new Product("T-Shirt","","12-02-2024",500,ProductType.CLOTHES,"Krushnamurthy",ProductWarrentyYear.ONE,false,1001,"India");
		Product product112 =new Product("T-Shirt","","12-02-2024",500,ProductType.CLOTHES,"Krushnamurthy",ProductWarrentyYear.ONE,false,1001,"India");
		Product product113 =new Product("T-Shirt","","12-02-2024",500,ProductType.CLOTHES,"Krushnamurthy",ProductWarrentyYear.ONE,false,1001,"India");
		Product product114 =new Product("T-Shirt","","12-02-2024",500,ProductType.CLOTHES,"Krushnamurthy",ProductWarrentyYear.ONE,false,1001,"India");
		Product product115 =new Product("T-Shirt","","12-02-2024",500,ProductType.CLOTHES,"Krushnamurthy",ProductWarrentyYear.ONE,false,1001,"India");
		Product product116 =new Product("T-Shirt","","12-02-2024",500,ProductType.CLOTHES,"Krushnamurthy",ProductWarrentyYear.ONE,false,1001,"India");
		Product product117 =new Product("T-Shirt","","12-02-2024",500,ProductType.CLOTHES,"Krushnamurthy",ProductWarrentyYear.ONE,false,1001,"India");
		Product product118 =new Product("T-Shirt","","12-02-2024",500,ProductType.CLOTHES,"Krushnamurthy",ProductWarrentyYear.ONE,false,1001,"India");
		Product product119 =new Product("T-Shirt","","12-02-2024",500,ProductType.CLOTHES,"Krushnamurthy",ProductWarrentyYear.ONE,false,1001,"India");
		Product product120 =new Product("T-Shirt","","12-02-2024",500,ProductType.CLOTHES,"Krushnamurthy",ProductWarrentyYear.ONE,false,1001,"India");
		Product product121 =new Product("T-Shirt","","12-02-2024",500,ProductType.CLOTHES,"Krushnamurthy",ProductWarrentyYear.ONE,false,1001,"India");
		Product product122 =new Product("T-Shirt","","12-02-2024",500,ProductType.CLOTHES,"Krushnamurthy",ProductWarrentyYear.ONE,false,1001,"India");
		Product product123 =new Product("T-Shirt","","12-02-2024",500,ProductType.CLOTHES,"Krushnamurthy",ProductWarrentyYear.ONE,false,1001,"India");
		Product product124 =new Product("T-Shirt","","12-02-2024",500,ProductType.CLOTHES,"Krushnamurthy",ProductWarrentyYear.ONE,false,1001,"India");
		Product product125 =new Product("T-Shirt","","12-02-2024",500,ProductType.CLOTHES,"Krushnamurthy",ProductWarrentyYear.ONE,false,1001,"India");
		Product product126 =new Product("T-Shirt","","12-02-2024",500,ProductType.CLOTHES,"Krushnamurthy",ProductWarrentyYear.ONE,false,1001,"India");
		Product product127 =new Product("T-Shirt","","12-02-2024",500,ProductType.CLOTHES,"Krushnamurthy",ProductWarrentyYear.ONE,false,1001,"India");
		Product product128 =new Product("T-Shirt","","12-02-2024",500,ProductType.CLOTHES,"Krushnamurthy",ProductWarrentyYear.ONE,false,1001,"India");
		Product product129 =new Product("T-Shirt","","12-02-2024",500,ProductType.CLOTHES,"Krushnamurthy",ProductWarrentyYear.ONE,false,1001,"India");
		Product product130 =new Product("T-Shirt","","12-02-2024",500,ProductType.CLOTHES,"Krushnamurthy",ProductWarrentyYear.ONE,false,1001,"India");
		Product product131 =new Product("T-Shirt","","12-02-2024",500,ProductType.CLOTHES,"Krushnamurthy",ProductWarrentyYear.ONE,false,1001,"India");
		Product product132 =new Product("T-Shirt","","12-02-2024",500,ProductType.CLOTHES,"Krushnamurthy",ProductWarrentyYear.ONE,false,1001,"India");
		Product product133 =new Product("T-Shirt","","12-02-2024",500,ProductType.CLOTHES,"Krushnamurthy",ProductWarrentyYear.ONE,false,1001,"India");
		Product product134 =new Product("T-Shirt","","12-02-2024",500,ProductType.CLOTHES,"Krushnamurthy",ProductWarrentyYear.ONE,false,1001,"India");
		Product product135 =new Product("T-Shirt","","12-02-2024",500,ProductType.CLOTHES,"Krushnamurthy",ProductWarrentyYear.ONE,false,1001,"India");
	
		Product[] products = new Product[150];
		ProductOperation store= new ProductOperation(products);
		store.save(product);
		store.save(product3);
		
		System.out.println("----------------->>>>>>");
		Product[] matireals =new Product[11];
		ProductOperation saves=new ProductOperation(matireals);
		saves.save(product);
		saves.save(product1);
		saves.save(product2);
		saves.save(product3);
		saves.save(product4);
		saves.save(product5);
		saves.save(product6);
		saves.save(product7);
		saves.save(product8);
		saves.save(product9);
		saves.save(product10);
		
		System.out.println("------>>>>>>>>>>");
		
		store.search(1001);
		store.search(1003);
		System.out.println("------------->>>>>>>>>");
		store.search(1001,"T-Shirt");
		store.search(1003,"Santoor");
		
		System.out.println("---------->>>>>");
		store.search(1001,"T-Shirt","India");
		
		System.out.println("----->>>>>>>>>>");
		store.search("India");
		
		System.out.println("------------>>>>>>>>>>>>");
		store.check(1001,false);
		
		System.out.println("--------------->>>>>>>>>>>>>>>>>>>>");
		
		store.displayAllProducts(product);
		store.displayAllProducts(product1);
		store.displayAllProducts(product2);
		store.displayAllProducts(product3);
		store.displayAllProducts(product4);
		store.displayAllProducts(product5);
		store.displayAllProducts(product6);
		store.displayAllProducts(product7);
		store.displayAllProducts(product8);
		store.displayAllProducts(product9);
		store.displayAllProducts(product10);
		store.displayAllProducts(product11);
		store.displayAllProducts(product12);
		store.displayAllProducts(product13);
		store.displayAllProducts(product14);
		store.displayAllProducts(product15);
		store.displayAllProducts(product16);
		store.displayAllProducts(product17);
		store.displayAllProducts(product18);
		store.displayAllProducts(product19);
		store.displayAllProducts(product20);
		store.displayAllProducts(product21);
		store.displayAllProducts(product22);
		store.displayAllProducts(product23);
		store.displayAllProducts(product24);
		store.displayAllProducts(product25);
		store.displayAllProducts(product26);
		store.displayAllProducts(product27);
		store.displayAllProducts(product28);
		store.displayAllProducts(product29);
		store.displayAllProducts(product30);
		store.displayAllProducts(product31);
		store.displayAllProducts(product32);
		store.displayAllProducts(product33);
		store.displayAllProducts(product34);
		store.displayAllProducts(product35);
		store.displayAllProducts(product36);
		store.displayAllProducts(product37);
		store.displayAllProducts(product38);
		store.displayAllProducts(product39);
		store.displayAllProducts(product40);
		store.displayAllProducts(product41);
		store.displayAllProducts(product42);
		store.displayAllProducts(product43);
		store.displayAllProducts(product44);
		store.displayAllProducts(product45);
		store.displayAllProducts(product46);
		store.displayAllProducts(product47);
		store.displayAllProducts(product48);
		store.displayAllProducts(product49);
		store.displayAllProducts(product50);
		store.displayAllProducts(product51);
		store.displayAllProducts(product52);
		store.displayAllProducts(product53);
		store.displayAllProducts(product54);
		store.displayAllProducts(product55);
		store.displayAllProducts(product56);
		store.displayAllProducts(product57);
		store.displayAllProducts(product58);
		store.displayAllProducts(product59);
		store.displayAllProducts(product60);
		store.displayAllProducts(product61);
		store.displayAllProducts(product62);
		store.displayAllProducts(product63);
		store.displayAllProducts(product64);
		store.displayAllProducts(product65);
		store.displayAllProducts(product66);
		store.displayAllProducts(product67);
		store.displayAllProducts(product68);
		store.displayAllProducts(product69);
		store.displayAllProducts(product70);
		store.displayAllProducts(product71);
		store.displayAllProducts(product72);
		store.displayAllProducts(product73);
		store.displayAllProducts(product74);
		store.displayAllProducts(product75);
		store.displayAllProducts(product76);
		store.displayAllProducts(product77);
		store.displayAllProducts(product78);
		store.displayAllProducts(product79);
		store.displayAllProducts(product80);
		store.displayAllProducts(product81);
		store.displayAllProducts(product82);
		store.displayAllProducts(product83);
		store.displayAllProducts(product84);
		store.displayAllProducts(product85);
		store.displayAllProducts(product86);
		store.displayAllProducts(product87);
		store.displayAllProducts(product88);
		store.displayAllProducts(product89);
		store.displayAllProducts(product90);
		store.displayAllProducts(product91);
		store.displayAllProducts(product92);
		store.displayAllProducts(product93);
		store.displayAllProducts(product94);
		store.displayAllProducts(product95);
		store.displayAllProducts(product96);
		store.displayAllProducts(product97);
		store.displayAllProducts(product98);
		store.displayAllProducts(product99);
		store.displayAllProducts(product100);
		store.displayAllProducts(product101);
		store.displayAllProducts(product102);
		store.displayAllProducts(product103);
		store.displayAllProducts(product104);
		store.displayAllProducts(product105);
		store.displayAllProducts(product106);
		store.displayAllProducts(product107);
		store.displayAllProducts(product108);
		store.displayAllProducts(product109);
		store.displayAllProducts(product110);
		store.displayAllProducts(product111);
		store.displayAllProducts(product112);
		store.displayAllProducts(product113);
		store.displayAllProducts(product114);
		store.displayAllProducts(product115);
		store.displayAllProducts(product116);
		store.displayAllProducts(product117);
		store.displayAllProducts(product118);
		store.displayAllProducts(product119);
		store.displayAllProducts(product120);
		store.displayAllProducts(product121);
		store.displayAllProducts(product122);
		store.displayAllProducts(product123);
		store.displayAllProducts(product124);
		store.displayAllProducts(product125);
		store.displayAllProducts(product126);
		store.displayAllProducts(product127);
		store.displayAllProducts(product128);
		store.displayAllProducts(product129);
		store.displayAllProducts(product130);
		store.displayAllProducts(product131);
		store.displayAllProducts(product132);
		store.displayAllProducts(product133);
		store.displayAllProducts(product134);
		

		
		
		
		System.out.println("--------------->>>>>>>>>>>");
		store.get(ProductType.CLOTHES);
		
		System.out.println("----------->>>>>>>>>>>>>>>>>>");
		store.get(ProductWarrentyYear.ONE);
		
		
	}
}