class HotelRunner{
	public static void main(String[] args){
		String itemName= "Roti";
		int quantity=5;
		boolean parcel=true;
		Hotel.hotelOrder(itemName,quantity,parcel);
		itemName= "Masala Dosa";
		quantity=6;
		parcel=true;
		Hotel.hotelOrder(itemName,quantity,parcel);
		itemName= "Set Dosa";
		quantity=3;
		parcel=true
		Hotel.hotelOrder(itemName,quantity,parcel);
		itemName= "Idli";
		quantity=4;
		parcel=true;
		Hotel.hotelOrder(itemName,quantity,parcel);
		itemName= "Pallav";
		quantity=20;
		parcel=false;
		Hotel.hotelOrder(itemName,quantity,parcel);
		itemName= "Chitranna";
		quantity=8;
		parcel=false;
		Hotel.hotelOrder(itemName,quantity,parcel);
		itemName= "Pulihogare";
		quantity=5;
		parcel=true;
		Hotel.hotelOrder(itemName,quantity,parcel);
		itemName= "Uppittu";
		quantity=3;
		parcel=true;
		Hotel.hotelOrder(itemName,quantity,parcel);
		itemName= "Tamoto RIce";
		quantity=4;
		parcel=true;
		Hotel.hotelOrder(itemName,quantity,parcel);
		itemName= "Curd Rice";
		quantity=10;
		parcel=true;
		Hotel.hotelOrder(itemName,quantity,parcel);
		itemName= "Jeera Rice";
		quantity=10;
		parcel=false;
		Hotel.hotelOrder(itemName,quantity,parcel);
		itemName= "Masala Rice";
		quantity=5;
		parcel=false;
		Hotel.hotelOrder(itemName,quantity,parcel);
		itemName= "Egg Rice";
		quantity=8;
		parcel=true;
		Hotel.hotelOrder(itemName,quantity,parcel);
		itemName= "Pride Rice";
		quantity=3;
		parcel=true;
		Hotel.hotelOrder(itemName,quantity,parcel);
		itemName= "Tanduri Roti";
		quantity=8;
		parcel=true;
		Hotel.hotelOrder(itemName,quantity,parcel);
		itemName= "Dall";
		quantity=2;
		parcel=true;
		Hotel.hotelOrder(itemName,quantity,parcel);
		itemName= "Pannir TIkka";
		quantity=2;
		parcel=true;
		Hotel.hotelOrder(itemName,quantity,parcel);
		itemName= "Chikken TIkka";
		quantity=2;
		parcel=true;
		Hotel.hotelOrder(itemName,quantity,parcel);
		itemName= "Tandoori CHikken";
		quantity=23;
		parcel=false;
		Hotel.hotelOrder(itemName,quantity,parcel);
		itemName= "Fish Amritsare";
		quantity=2;
		parcel=true;
		Hotel.hotelOrder(itemName,quantity,parcel);
		itemName= "Seekh Kabab";
		quantity=2;
		parcel=true;
		Hotel.hotelOrder(itemName,quantity,parcel);
		itemName= "Masala Papad";
		quantity=3;
		parcel=true;
		Hotel.hotelOrder(itemName,quantity,parcel);
		itemName= "Dal Makhani";
		quantity=3;
		parcel=true;
		Hotel.hotelOrder(itemName,quantity,parcel);
		itemName= "Dal Tadka";
		quantity=3;
		parcel=false;
		Hotel.hotelOrder(itemName,quantity,parcel);
		itemName= "Paneer Butter Masal";
		quantity=4;
		parcel=true;
		Hotel.hotelOrder(itemName,quantity,parcel);
		itemName= "Kadhai Paneer";
		quantity=4;
		parcel=true;
		Hotel.hotelOrder(itemName,quantity,parcel);
		itemName= "Mix veg";
		quantity=4;
		parcel=true;
		Hotel.hotelOrder(itemName,quantity,parcel);
		itemName= "Aloo Gobhi";
		quantity=4;
		parcel=true;
		Hotel.hotelOrder(itemName,quantity,parcel);
		itemName= "Baingan Bharta";
		quantity=2;
		parcel=true;
		Hotel.hotelOrder(itemName,quantity,parcel);
		itemName= "Bhindi DO Pyaza";
		quantity=1;
		parcel=true;
		Hotel.hotelOrder(itemName,quantity,parcel);
		itemName= "Malai Kofta";
		quantity=1;
		parcel=true;
		Hotel.hotelOrder(itemName,quantity,parcel);
		itemName= "Chana Masala";
		quantity=3;
		parcel=true;
		Hotel.hotelOrder(itemName,quantity,parcel);
		itemName= "Mushroom Matar";
		quantity=7;
		parcel=false;
		Hotel.hotelOrder(itemName,quantity,parcel);
		itemName= "Sarson Saag";
		quantity=3;
		parcel=true;
		Hotel.hotelOrder(itemName,quantity,parcel);
		itemName= "Butter Chikken";
		quantity=9;
		parcel=true;
		Hotel.hotelOrder(itemName,quantity,parcel);
		itemName= "Chicken CUrry";
		quantity=3;
		parcel=true;
		Hotel.hotelOrder(itemName,quantity,parcel);
		itemName= "Mixed Veg Raita";
		quantity=1;
		parcel=true;
		Hotel.hotelOrder(itemName,quantity,parcel);
		itemName= "Boondi Raita";
		quantity=1;
		parcel=true;
		Hotel.hotelOrder(itemName,quantity,parcel);
		itemName= "Sirka Pyaaz";
		quantity=1;
		parcel=true;
		Hotel.hotelOrder(itemName,quantity,parcel);
		itemName= "Fresh Green Salad";
		quantity=2;
		parcel=true;
		Hotel.hotelOrder(itemName,quantity,parcel);
		itemName= "Sweet Lessi";
		quantity=2;
		parcel=true;
		Hotel.hotelOrder(itemName,quantity,parcel);
		itemName= "Masala Chaas";
		quantity=32;
		parcel=false;
		Hotel.hotelOrder(itemName,quantity,parcel);
		quantity=2;
		parcel=true;
		Hotel.hotelOrder(itemName,quantity,parcel);
		itemName= "Gulab Jamun";
		quantity=10;
		parcel=true;
		Hotel.hotelOrder(itemName,quantity,parcel);
		itemName= "Gajar Ka Halwa";
		quantity=1;
		parcel=true;
		Hotel.hotelOrder(itemName,quantity,parcel);
		itemName= "Sprite";
		quantity=9;
		parcel=true;
		Hotel.hotelOrder(itemName,quantity,parcel);
		itemName= "Slice";
		quantity=7;
		parcel=true;
		Hotel.hotelOrder(itemName,quantity,parcel);
		itemName= "Coco";
		quantity=7;
		parcel=true;
		Hotel.hotelOrder(itemName,quantity,parcel);
		itemName= "Mango";
		quantity=3;
		 parcel=true;
		Hotel.hotelOrder(itemName,quantity,parcel);
		itemName= "Bindhu";
		quantity=9;
		parcel=true;
		Hotel.hotelOrder(itemName,quantity,parcel);
		itemName= "Miranda";
		quantity=2;
		parcel=true;
		Hotel.hotelOrder(itemName,quantity,parcel);
	}
}