class StaffRunner{
	public static void main(String []args){
		String type= "School Principal";
		String staffName= "Balaji";
		int salary=60000;
		String nativity= "Shivmoga";
		String email= "balaji12@gmail.com";
		int mobileNo=9845580918;
		Staff.staffInfo(type,staffName,salary,nativity,email,mobileNo);
		type= "Vice Principal";
		staffName= "Umesh M N";
		salary=50000;
		nativity= "Kaknur";
		email= "umesh123@gmail.com";
		mobileNo=9876567876;
		Staff.staffInfo(type,staffName,salary,nativity,email,mobileNo);
		type= "Dean";
		staffName= "Lakshman";
		salary=12000;
		nativity= "Bangalore";
		email= "lakshman43@gmail.com";
		mobileNo=9865787456;
		Staff.staffInfo(type,staffName,salary,nativity,email,mobileNo);
		type= "Professor";
		staffName= "Shridar";
		salary=9000;
		nativity= "hodigere";
		email= "shridar56@gmail.com";
		mobileNo=9865746545;
		Staff.staffInfo(type,staffName,salary,nativity,email,mobileNo);
		type= "Lecture";
		staffName= "Maruthi";
		salary=15000;
		nativity= "Pavagada";
		email= "maruthi23@gmai.com";
		mobileNo=7665456381;
		Staff.staffInfo(type,staffName,salary,nativity,email,mobileNo);
		type= "Teching Assistant";
		String staffName= "Shivu Kumar";
		salary=80000;
		nativity= "Channagri";
		email= "Shivu43@gmail.com";
		mobileNo=9865453532;
		Staff.staffInfo(type,staffName,salary,nativity,email,mobileNo);
		type= "School Counselor";
		staffName= "Rajesh";
		salary=17000;
		nativity= "Channagiri";
		email= "";
		mobileNo=71726546763;
		Staff.staffInfo(type,staffName,salary,nativity,email,mobileNo);
		type= "Librarian";
		staffName= "Ganesh";
		salary=20000;
		nativity= "Bangalore";
		email= "ganesh91@gmail.com";
		mobileNo=9845590461;
		Staff.staffInfo(type,staffName,salary,nativity,email,mobileNo);
		type= "Rehistrar";
		staffName= "Shambulinga";
		salary=60000;
		nativity= "Kalburgi";
		email= "Shambu76@gmail.com";
		mobileNo=7864657464;
		Staff.staffInfo(type,staffName,salary,nativity,email,mobileNo);
		type= "Admissions Officer";
		staffName= "Prasanna";
		salary=150000;
		nativity= "Hodigere";
		email= "prasanna45@gmail.com";
		mobileNo=6362724663;
		Staff.staffInfo(type,staffName,salary,nativity,email,mobileNo);
		type= "Special Education Teacher";
		staffName= "Kumar";
		salary=50000;
		nativity= "Chitradurga";
		email= "kumar12@gmail.com";
		mobileNo=9845590873;
		Staff.staffInfo(type,staffName,salary,nativity,email,mobileNo);
		type= "Substitute Teacher";
		staffName= "Subhash";
		salary=70000;
		nativity= "Karvar";
		email= "subhash65@gmiail.com";
		mobileNo=9876467464;
		Staff.staffInfo(type,staffName,salary,nativity,email,mobileNo);
		type= "ESL Instuctor";
		staffName= "Pratham";
		salary=35000;
		nativity= "channai";
		email= "prathu36@gmail.com";
		mobileNo=4362636345;
		Staff.staffInfo(type,staffName,salary,nativity,email,mobileNo);
		type= "Lab Assistant";
		staffName= "Paramesh";
		salary=70000;
		nativity= "Holalkere";
		email= "param3453@gmail.com";
		mobileNo=9845590398;
		Staff.staffInfo(type,staffName,salary,nativity,email,mobileNo);
		type= "Career Coach";
		staffName= "Siddesh";
		salary=23000;
		nativity= "Belagam";
		email= "siddu35@gmail.com";
		mobileNo=9874648698;
		Staff.staffInfo(type,staffName,salary,nativity,email,mobileNo);
		type= "Janitor";
		staffName= "Kiran ";
		salary=87000;
		nativity= "Bijapur";
		email= "kiran89@gmail.com";
		mobileNo=7564647448;
		Staff.staffInfo(type,staffName,salary,nativity,email,mobileNo);
		type= "Bus Driver";
		staffName= "Nagaprajwal";
		salary=100000;
		nativity= "Hiriyur";
		email= "naga54@gmail.com";
		mobileNo=7564645354;
		Staff.staffInfo(type,staffName,salary,nativity,email,mobileNo);
		type= "Cafeteria";
		staffName= "Harish";
		salary=7665655469;
		nativity= "Tumkur";
		email= "harish5@gmail.com";
		mobileNo=9878988754;
		Staff.staffInfo(type,staffName,salary,nativity,email,mobileNo);
		type= "Security Guard";
		staffName= "Sudeep";
		salary=89000;
		nativity= "Bijapur";
		email= "sudi43@gmail.com";
		mobileNo=9807667598;
		Staff.staffInfo(type,staffName,salary,nativity,email,mobileNo);
		type= "Student Advisor";
		staffName= "Vishwa";
		salary=45000;
		nativity= "Kerala";
		email= "vishw989@gmail.com";
		mobileNo=8776564653;
		Staff.staffInfo(type,staffName,salary,nativity,email,mobileNo);
		type= "Software Engineer";
		staffName= "Raghu";
		salary=80000;
		nativity= "Kop";
		email= "raghu73@gmail.com";
		mobileNo=8765768675;
		Staff.staffInfo(type,staffName,salary,nativity,email,mobileNo);
		type= "Frontend Developer";
		staffName= "Madhan";
		salary=87834;
		nativity= "Odisha";
		email= "raaghu73@gmail.com";
		mobileNo=8765768677;
		Staff.staffInfo(type,staffName,salary,nativity,email,mobileNo);
		type= "Backend Developer";
		staffName= "Aishwarya";
		salary=56669;
		nativity= "Shivmoga";
		email= "Aush32@gmail.com";
		mobileNo=8765768689;
		Staff.staffInfo(type,staffName,salary,nativity,email,mobileNo);
		type= "FullStack Devloper";
		staffName= "Ankithaa";
		salary=76888;
		nativity= "Hodigere";
		email= "anku77@gmail.com";
		 mobileNo=8765768867;
		Staff.staffInfo(type,staffName,salary,nativity,email,mobileNo);
		type= "System Engineer";
		staffName= "Rakshitha";
		salary=546564;
		nativity= "Hodigeree";
		email= "raksh43@gmail.com";
		mobileNo=8765768978;
		Staff.staffInfo(type,staffName,salary,nativity,email,mobileNo);
		type= "Network Engineer";
		staffName= "Ananya";
		salary=878686;
		nativity= "Benkikere";
		email= "anu@gmail.com";
		mobileNo=8765768768;
		Staff.staffInfo(type,staffName,salary,nativity,email,mobileNo);
		type= "CyberSecurity Engineer";
		staffName= "Radhika";
		salary=86768;
		nativity= "Harihar";
		email= "radhika53@gmail.com";
		mobileNo=8765768434;
		Staff.staffInfo(type,staffName,salary,nativity,email,mobileNo);
		type= "Database Administrator";
		staffName= "Vanitha";
		salary=888868;
		nativity= "Challakere";
		email= "vanitha53@gmail.com";
		mobileNo=876576765;
		Staff.staffInfo(type,staffName,salary,nativity,email,mobileNo);
		type= "IT Support Technician ";
		staffName= "Keerthana";
		salary=979897;
		nativity= "Challakeree";
		email= "kerrtha@gmail.com";
		mobileNo=8765768670;
		Staff.staffInfo(type,staffName,salary,nativity,email,mobileNo);
		type= "Cloud Architech";
		staffName= "Sanjana";
		salary=857573;
		nativity= "Channnagiri";
		email= "sanju43@gmail.com";
		mobileNo=8765768680;
		Staff.staffInfo(type,staffName,salary,nativity,email,mobileNo);
		type= "UX/UI Designer";
		staffName= "Prathibha";
		salary=84585;
		nativity= "Billahhi";
		email= "prathi4@gmail.com";
		mobileNo=8765768672;
		Staff.staffInfo(type,staffName,salary,nativity,email,mobileNo);
		type= "Quality Assurance Tester";
		staffName= "Varun";
		salary=766576;
		nativity= "Shivagange";
		email= "varu4@gmail.com";
		mobileNo=8765768643;
		Staff.staffInfo(type,staffName,salary,nativity,email,mobileNo);
		type= "DevOps Engineer";
		staffName= "Prajju";
		salary=76857;
		nativity= "Hiriyur";
		email= "praju74@gmail.com";
		mobileNo=8765768432;
		Staff.staffInfo(type,staffName,salary,nativity,email,mobileNo);
		type= "Data Scietist";
		staffName="Karthik";
		salary=854858;
		nativity= "Bidikere";
		email= "karthik5@gmail.com";
		mobileNo=8765768675;
		Staff.staffInfo(type,staffName,salary,nativity,email,mobileNo);
		String type= "School Principal";
		String staffName= "Balaji";
		int salary=60000;
		String nativity= "Shivmoga";
		String email= "balaji12@gmail.com";
		int mobileNo=9845580918;
		Staff.staffInfo(type,staffName,salary,nativity,email,mobileNo);
		type= "Vice Principal";
		staffName= "Umesh M N";
		salary=50000;
		nativity= "Kaknur";
		email= "umesh123@gmail.com";
		mobileNo=9876567876;
		Staff.staffInfo(type,staffName,salary,nativity,email,mobileNo);
		type= "Dean";
		staffName= "Lakshman";
		salary=12000;
		nativity= "Bangalore";
		email= "lakshman43@gmail.com";
		mobileNo=9865787456;
		Staff.staffInfo(type,staffName,salary,nativity,email,mobileNo);
		type= "Professor";
		staffName= "Shridar";
		salary=9000;
		nativity= "hodigere";
		email= "shridar56@gmail.com";
		mobileNo=9865746545;
		Staff.staffInfo(type,staffName,salary,nativity,email,mobileNo);
		type= "Lecture";
		staffName= "Maruthi";
		salary=15000;
		nativity= "Pavagada";
		email= "maruthi23@gmai.com";
		mobileNo=7665456381;
		Staff.staffInfo(type,staffName,salary,nativity,email,mobileNo);
		type= "Teching Assistant";
		String staffName= "Shivu Kumar";
		salary=80000;
		nativity= "Channagri";
		email= "Shivu43@gmail.com";
		mobileNo=9865453532;
		Staff.staffInfo(type,staffName,salary,nativity,email,mobileNo);
		type= "School Counselor";
		staffName= "Rajesh";
		salary=17000;
		nativity= "Channagiri";
		email= "";
		mobileNo=71726546763;
		Staff.staffInfo(type,staffName,salary,nativity,email,mobileNo);
		type= "Librarian";
		staffName= "Ganesh";
		salary=20000;
		nativity= "Bangalore";
		email= "ganesh91@gmail.com";
		mobileNo=9845590461;
		Staff.staffInfo(type,staffName,salary,nativity,email,mobileNo);
		type= "Rehistrar";
		staffName= "Shambulinga";
		salary=60000;
		nativity= "Kalburgi";
		email= "Shambu76@gmail.com";
		mobileNo=7864657464;
		Staff.staffInfo(type,staffName,salary,nativity,email,mobileNo);
		type= "Admissions Officer";
		staffName= "Prasanna";
		salary=150000;
		nativity= "Hodigere";
		email= "prasanna45@gmail.com";
		mobileNo=6362724663;
		Staff.staffInfo(type,staffName,salary,nativity,email,mobileNo);
		type= "Special Education Teacher";
		staffName= "Kumar";
		salary=50000;
		nativity= "Chitradurga";
		email= "kumar12@gmail.com";
		mobileNo=9845590873;
		Staff.staffInfo(type,staffName,salary,nativity,email,mobileNo);
		type= "Substitute Teacher";
		staffName= "Subhash";
		salary=70000;
		nativity= "Karvar";
		email= "subhash65@gmiail.com";
		mobileNo=9876467464;
		Staff.staffInfo(type,staffName,salary,nativity,email,mobileNo);
		type= "ESL Instuctor";
		staffName= "Pratham";
		salary=35000;
		nativity= "channai";
		email= "prathu36@gmail.com";
		mobileNo=4362636345;
		Staff.staffInfo(type,staffName,salary,nativity,email,mobileNo);
		type= "Lab Assistant";
		staffName= "Paramesh";
		salary=70000;
		nativity= "Holalkere";
		email= "param3453@gmail.com";
		mobileNo=9845590398;
		Staff.staffInfo(type,staffName,salary,nativity,email,mobileNo);
		type= "Career Coach";
		staffName= "Siddesh";
		salary=23000;
		nativity= "Belagam";
		email= "siddu35@gmail.com";
		mobileNo=9874648698;
		Staff.staffInfo(type,staffName,salary,nativity,email,mobileNo);
		type= "Janitor";
		staffName= "Kiran ";
		salary=87000;
		nativity= "Bijapur";
		email= "kiran89@gmail.com";
		mobileNo=7564647448;
		Staff.staffInfo(type,staffName,salary,nativity,email,mobileNo);
		type= "Bus Driver";
		staffName= "Nagaprajwal";
		salary=100000;
		nativity= "Hiriyur";
		email= "naga54@gmail.com";
		mobileNo=7564645354;
		Staff.staffInfo(type,staffName,salary,nativity,email,mobileNo);
		type= "Cafeteria";
		staffName= "Harish";
		salary=7665655469;
		nativity= "Tumkur";
		email= "harish5@gmail.com";
		mobileNo=9878988754;
		Staff.staffInfo(type,staffName,salary,nativity,email,mobileNo);
		type= "Security Guard";
		staffName= "Sudeep";
		salary=89000;
		nativity= "Bijapur";
		email= "sudi43@gmail.com";
		mobileNo=9807667598;
		Staff.staffInfo(type,staffName,salary,nativity,email,mobileNo);
		type= "Student Advisor";
		staffName= "Vishwa";
		salary=45000;
		nativity= "Kerala";
		email= "vishw989@gmail.com";
		mobileNo=8776564653;
		Staff.staffInfo(type,staffName,salary,nativity,email,mobileNo);
		type= "Software Engineer";
		staffName= "Raghu";
		salary=80000;
		nativity= "Kop";
		email= "raghu73@gmail.com";
		mobileNo=8765768675;
		Staff.staffInfo(type,staffName,salary,nativity,email,mobileNo);
		type= "Frontend Developer";
		staffName= "Madhan";
		salary=87834;
		nativity= "Odisha";
		email= "raaghu73@gmail.com";
		mobileNo=8765768677;
		Staff.staffInfo(type,staffName,salary,nativity,email,mobileNo);
		type= "Backend Developer";
		staffName= "Aishwarya";
		salary=56669;
		nativity= "Shivmoga";
		email= "Aush32@gmail.com";
		mobileNo=8765768689;
		Staff.staffInfo(type,staffName,salary,nativity,email,mobileNo);
		type= "FullStack Devloper";
		staffName= "Ankithaa";
		salary=76888;
		nativity= "Hodigere";
		email= "anku77@gmail.com";
		 mobileNo=8765768867;
		Staff.staffInfo(type,staffName,salary,nativity,email,mobileNo);
		type= "System Engineer";
		staffName= "Rakshitha";
		salary=546564;
		nativity= "Hodigeree";
		email= "raksh43@gmail.com";
		mobileNo=8765768978;
		Staff.staffInfo(type,staffName,salary,nativity,email,mobileNo);
		type= "Network Engineer";
		staffName= "Ananya";
		salary=878686;
		nativity= "Benkikere";
		email= "anu@gmail.com";
		mobileNo=8765768768;
		Staff.staffInfo(type,staffName,salary,nativity,email,mobileNo);
		type= "CyberSecurity Engineer";
		staffName= "Radhika";
		salary=86768;
		nativity= "Harihar";
		email= "radhika53@gmail.com";
		mobileNo=8765768434;
		Staff.staffInfo(type,staffName,salary,nativity,email,mobileNo);
		type= "Database Administrator";
		staffName= "Vanitha";
		salary=888868;
		nativity= "Challakere";
		email= "vanitha53@gmail.com";
		mobileNo=876576765;
		Staff.staffInfo(type,staffName,salary,nativity,email,mobileNo);
		type= "IT Support Technician ";
		staffName= "Keerthana";
		salary=979897;
		nativity= "Challakeree";
		email= "kerrtha@gmail.com";
		mobileNo=8765768670;
		Staff.staffInfo(type,staffName,salary,nativity,email,mobileNo);
		type= "Cloud Architech";
		staffName= "Sanjana";
		salary=857573;
		nativity= "Channnagiri";
		email= "sanju43@gmail.com";
		mobileNo=8765768680;
		Staff.staffInfo(type,staffName,salary,nativity,email,mobileNo);
		type= "UX/UI Designer";
		staffName= "Prathibha";
		salary=84585;
		nativity= "Billahhi";
		email= "prathi4@gmail.com";
		mobileNo=8765768672;
		Staff.staffInfo(type,staffName,salary,nativity,email,mobileNo);
		type= "Quality Assurance Tester";
		staffName= "Varun";
		salary=766576;
		nativity= "Shivagange";
		email= "varu4@gmail.com";
		mobileNo=8765768643;
		Staff.staffInfo(type,staffName,salary,nativity,email,mobileNo);
		type= "DevOps Engineer";
		staffName= "Prajju";
		salary=76857;
		nativity= "Hiriyur";
		email= "praju74@gmail.com";
		mobileNo=8765768432;
		Staff.staffInfo(type,staffName,salary,nativity,email,mobileNo);
		type= "Data Scietist";
		staffName="Karthik";
		salary=854858;
		nativity= "Bidikere";
		email= "karthik5@gmail.com";
		mobileNo=8765768675;
		Staff.staffInfo(type,staffName,salary,nativity,email,mobileNo);
		String type= "School Principal";
		String staffName= "Balaji";
		int salary=60000;
		String nativity= "Shivmoga";
		String email= "balaji12@gmail.com";
		int mobileNo=9845580918;
		Staff.staffInfo(type,staffName,salary,nativity,email,mobileNo);
		type= "Vice Principal";
		staffName= "Umesh M N";
		salary=50000;
		nativity= "Kaknur";
		email= "umesh123@gmail.com";
		mobileNo=9876567876;
		Staff.staffInfo(type,staffName,salary,nativity,email,mobileNo);
		type= "Dean";
		staffName= "Lakshman";
		salary=12000;
		nativity= "Bangalore";
		email= "lakshman43@gmail.com";
		mobileNo=9865787456;
		Staff.staffInfo(type,staffName,salary,nativity,email,mobileNo);
		type= "Professor";
		staffName= "Shridar";
		salary=9000;
		nativity= "hodigere";
		email= "shridar56@gmail.com";
		mobileNo=9865746545;
		Staff.staffInfo(type,staffName,salary,nativity,email,mobileNo);
		type= "Lecture";
		staffName= "Maruthi";
		salary=15000;
		nativity= "Pavagada";
		email= "maruthi23@gmai.com";
		mobileNo=7665456381;
		Staff.staffInfo(type,staffName,salary,nativity,email,mobileNo);
		type= "Teching Assistant";
		String staffName= "Shivu Kumar";
		salary=80000;
		nativity= "Channagri";
		email= "Shivu43@gmail.com";
		mobileNo=9865453532;
		Staff.staffInfo(type,staffName,salary,nativity,email,mobileNo);
		type= "School Counselor";
		staffName= "Rajesh";
		salary=17000;
		nativity= "Channagiri";
		email= "";
		mobileNo=71726546763;
		Staff.staffInfo(type,staffName,salary,nativity,email,mobileNo);
		type= "Librarian";
		staffName= "Ganesh";
		salary=20000;
		nativity= "Bangalore";
		email= "ganesh91@gmail.com";
		mobileNo=9845590461;
		Staff.staffInfo(type,staffName,salary,nativity,email,mobileNo);
		type= "Rehistrar";
		staffName= "Shambulinga";
		salary=60000;
		nativity= "Kalburgi";
		email= "Shambu76@gmail.com";
		mobileNo=7864657464;
		Staff.staffInfo(type,staffName,salary,nativity,email,mobileNo);
		type= "Admissions Officer";
		staffName= "Prasanna";
		salary=150000;
		nativity= "Hodigere";
		email= "prasanna45@gmail.com";
		mobileNo=6362724663;
		Staff.staffInfo(type,staffName,salary,nativity,email,mobileNo);
		type= "Special Education Teacher";
		staffName= "Kumar";
		salary=50000;
		nativity= "Chitradurga";
		email= "kumar12@gmail.com";
		mobileNo=9845590873;
		Staff.staffInfo(type,staffName,salary,nativity,email,mobileNo);
		type= "Substitute Teacher";
		staffName= "Subhash";
		salary=70000;
		nativity= "Karvar";
		email= "subhash65@gmiail.com";
		mobileNo=9876467464;
		Staff.staffInfo(type,staffName,salary,nativity,email,mobileNo);
		type= "ESL Instuctor";
		staffName= "Pratham";
		salary=35000;
		nativity= "channai";
		email= "prathu36@gmail.com";
		mobileNo=4362636345;
		Staff.staffInfo(type,staffName,salary,nativity,email,mobileNo);
		type= "Lab Assistant";
		staffName= "Paramesh";
		salary=70000;
		nativity= "Holalkere";
		email= "param3453@gmail.com";
		mobileNo=9845590398;
		Staff.staffInfo(type,staffName,salary,nativity,email,mobileNo);
		type= "Career Coach";
		staffName= "Siddesh";
		salary=23000;
		nativity= "Belagam";
		email= "siddu35@gmail.com";
		mobileNo=9874648698;
		Staff.staffInfo(type,staffName,salary,nativity,email,mobileNo);
		type= "Janitor";
		staffName= "Kiran ";
		salary=87000;
		nativity= "Bijapur";
		email= "kiran89@gmail.com";
		mobileNo=7564647448;
		Staff.staffInfo(type,staffName,salary,nativity,email,mobileNo);
		type= "Bus Driver";
		staffName= "Nagaprajwal";
		salary=100000;
		nativity= "Hiriyur";
		email= "naga54@gmail.com";
		mobileNo=7564645354;
		Staff.staffInfo(type,staffName,salary,nativity,email,mobileNo);
		type= "Cafeteria";
		staffName= "Harish";
		salary=7665655469;
		nativity= "Tumkur";
		email= "harish5@gmail.com";
		mobileNo=9878988754;
		Staff.staffInfo(type,staffName,salary,nativity,email,mobileNo);
		type= "Security Guard";
		staffName= "Sudeep";
		salary=89000;
		nativity= "Bijapur";
		email= "sudi43@gmail.com";
		mobileNo=9807667598;
		Staff.staffInfo(type,staffName,salary,nativity,email,mobileNo);
		type= "Student Advisor";
		staffName= "Vishwa";
		salary=45000;
		nativity= "Kerala";
		email= "vishw989@gmail.com";
		mobileNo=8776564653;
		Staff.staffInfo(type,staffName,salary,nativity,email,mobileNo);
		type= "Software Engineer";
		staffName= "Raghu";
		salary=80000;
		nativity= "Kop";
		email= "raghu73@gmail.com";
		mobileNo=8765768675;
		Staff.staffInfo(type,staffName,salary,nativity,email,mobileNo);
		type= "Frontend Developer";
		staffName= "Madhan";
		salary=87834;
		nativity= "Odisha";
		email= "raaghu73@gmail.com";
		mobileNo=8765768677;
		Staff.staffInfo(type,staffName,salary,nativity,email,mobileNo);
		type= "Backend Developer";
		staffName= "Aishwarya";
		salary=56669;
		nativity= "Shivmoga";
		email= "Aush32@gmail.com";
		mobileNo=8765768689;
		Staff.staffInfo(type,staffName,salary,nativity,email,mobileNo);
		type= "FullStack Devloper";
		staffName= "Ankithaa";
		salary=76888;
		nativity= "Hodigere";
		email= "anku77@gmail.com";
		 mobileNo=8765768867;
		Staff.staffInfo(type,staffName,salary,nativity,email,mobileNo);
		type= "System Engineer";
		staffName= "Rakshitha";
		salary=546564;
		nativity= "Hodigeree";
		email= "raksh43@gmail.com";
		mobileNo=8765768978;
		Staff.staffInfo(type,staffName,salary,nativity,email,mobileNo);
		type= "Network Engineer";
		staffName= "Ananya";
		salary=878686;
		nativity= "Benkikere";
		email= "anu@gmail.com";
		mobileNo=8765768768;
		Staff.staffInfo(type,staffName,salary,nativity,email,mobileNo);
		type= "CyberSecurity Engineer";
		staffName= "Radhika";
		salary=86768;
		nativity= "Harihar";
		email= "radhika53@gmail.com";
		mobileNo=8765768434;
		Staff.staffInfo(type,staffName,salary,nativity,email,mobileNo);
		type= "Database Administrator";
		staffName= "Vanitha";
		salary=888868;
		nativity= "Challakere";
		email= "vanitha53@gmail.com";
		mobileNo=876576765;
		Staff.staffInfo(type,staffName,salary,nativity,email,mobileNo);
		type= "IT Support Technician ";
		staffName= "Keerthana";
		salary=979897;
		nativity= "Challakeree";
		email= "kerrtha@gmail.com";
		mobileNo=8765768670;
		Staff.staffInfo(type,staffName,salary,nativity,email,mobileNo);
		type= "Cloud Architech";
		staffName= "Sanjana";
		salary=857573;
		nativity= "Channnagiri";
		email= "sanju43@gmail.com";
		mobileNo=8765768680;
		Staff.staffInfo(type,staffName,salary,nativity,email,mobileNo);
		type= "UX/UI Designer";
		staffName= "Prathibha";
		salary=84585;
		nativity= "Billahhi";
		email= "prathi4@gmail.com";
		mobileNo=8765768672;
		Staff.staffInfo(type,staffName,salary,nativity,email,mobileNo);
		type= "Quality Assurance Tester";
		staffName= "Varun";
		salary=766576;
		nativity= "Shivagange";
		email= "varu4@gmail.com";
		mobileNo=8765768643;
		Staff.staffInfo(type,staffName,salary,nativity,email,mobileNo);
		type= "DevOps Engineer";
		staffName= "Prajju";
		salary=76857;
		nativity= "Hiriyur";
		email= "praju74@gmail.com";
		mobileNo=8765768432;
		Staff.staffInfo(type,staffName,salary,nativity,email,mobileNo);
		type= "Data Scietist";
		staffName="Karthik";
		salary=854858;
		nativity= "Bidikere";
		email= "karthik5@gmail.com";
		mobileNo=8765768675;
		Staff.staffInfo(type,staffName,salary,nativity,email,mobileNo);
		String type= "School Principal";
		String staffName= "Balaji";
		int salary=60000;
		String nativity= "Shivmoga";
		String email= "balaji12@gmail.com";
		int mobileNo=9845580918;
		Staff.staffInfo(type,staffName,salary,nativity,email,mobileNo);
		type= "Vice Principal";
		staffName= "Umesh M N";
		salary=50000;
		nativity= "Kaknur";
		email= "umesh123@gmail.com";
		mobileNo=9876567876;
		Staff.staffInfo(type,staffName,salary,nativity,email,mobileNo);
		type= "Dean";
		staffName= "Lakshman";
		salary=12000;
		nativity= "Bangalore";
		email= "lakshman43@gmail.com";
		mobileNo=9865787456;
		Staff.staffInfo(type,staffName,salary,nativity,email,mobileNo);
		type= "Professor";
		staffName= "Shridar";
		salary=9000;
		nativity= "hodigere";
		email= "shridar56@gmail.com";
		mobileNo=9865746545;
		Staff.staffInfo(type,staffName,salary,nativity,email,mobileNo);
		type= "Lecture";
		staffName= "Maruthi";
		salary=15000;
		nativity= "Pavagada";
		email= "maruthi23@gmai.com";
		mobileNo=7665456381;
		Staff.staffInfo(type,staffName,salary,nativity,email,mobileNo);
		type= "Teching Assistant";
		String staffName= "Shivu Kumar";
		salary=8000;
		nativity= "Channagri";
		email= "Shivu43@gmail.com";
		mobileNo=9865453532;
		Staff.staffInfo(type,staffName,salary,nativity,email,mobileNo);
		type= "School Counselor";
		staffName= "Rajesh";
		salary=17000;
		nativity= "Channagiri";
		email= "";
		mobileNo=71726546763;
		Staff.staffInfo(type,staffName,salary,nativity,email,mobileNo);
		type= "Librarian";
		staffName= "Ganesh";
		salary=20000;
		nativity= "Bangalore";
		email= "ganesh91@gmail.com";
		mobileNo=9845590461;
		Staff.staffInfo(type,staffName,salary,nativity,email,mobileNo);
		type= "Rehistrar";
		staffName= "Shambulinga";
		salary=60000;
		nativity= "Kalburgi";
		email= "Shambu76@gmail.com";
		mobileNo=7864657464;
		Staff.staffInfo(type,staffName,salary,nativity,email,mobileNo);
		type= "Admissions Officer";
		staffName= "Prasanna";
		salary=150000;
		nativity= "Hodigere";
		email= "prasanna45@gmail.com";
		mobileNo=6362724663;
		Staff.staffInfo(type,staffName,salary,nativity,email,mobileNo);
		type= "Special Education Teacher";
		staffName= "Kumar";
		salary=50000;
		nativity= "Chitradurga";
		email= "kumar12@gmail.com";
		mobileNo=9845590873;
		Staff.staffInfo(type,staffName,salary,nativity,email,mobileNo);
		type= "Substitute Teacher";
		staffName= "Subhash";
		salary=70000;
		nativity= "Karvar";
		email= "subhash65@gmiail.com";
		mobileNo=9876467464;
		Staff.staffInfo(type,staffName,salary,nativity,email,mobileNo);
		type= "ESL Instuctor";
		staffName= "Pratham";
		salary=35000;
		nativity= "channai";
		email= "prathu36@gmail.com";
		mobileNo=4362636345;
		Staff.staffInfo(type,staffName,salary,nativity,email,mobileNo);
		type= "Lab Assistant";
		staffName= "Paramesh";
		salary=70000;
		nativity= "Holalkere";
		email= "param3453@gmail.com";
		mobileNo=9845590398;
		Staff.staffInfo(type,staffName,salary,nativity,email,mobileNo);
		type= "Career Coach";
		staffName= "Siddesh";
		salary=23000;
		nativity= "Belagam";
		email= "siddu35@gmail.com";
		mobileNo=9874648698;
		Staff.staffInfo(type,staffName,salary,nativity,email,mobileNo);
		type= "Janitor";
		staffName= "Kiran ";
		salary=87000;
		nativity= "Bijapur";
		email= "kiran89@gmail.com";
		mobileNo=7564647448;
		Staff.staffInfo(type,staffName,salary,nativity,email,mobileNo);
		type= "Bus Driver";
		staffName= "Nagaprajwal";
		salary=100000;
		nativity= "Hiriyur";
		email= "naga54@gmail.com";
		mobileNo=7564645354;
		Staff.staffInfo(type,staffName,salary,nativity,email,mobileNo);
		type= "Cafeteria";
		staffName= "Harish";
		salary=7665655469;
		nativity= "Tumkur";
		email= "harish5@gmail.com";
		mobileNo=9878988754;
		Staff.staffInfo(type,staffName,salary,nativity,email,mobileNo);
		type= "Security Guard";
		staffName= "Sudeep";
		salary=89000;
		nativity= "Bijapur";
		email= "sudi43@gmail.com";
		mobileNo=9807667598;
		Staff.staffInfo(type,staffName,salary,nativity,email,mobileNo);
		type= "Student Advisor";
		staffName= "Vishwa";
		salary=45000;
		nativity= "Kerala";
		email= "vishw989@gmail.com";
		mobileNo=8776564653;
		Staff.staffInfo(type,staffName,salary,nativity,email,mobileNo);
		type= "Software Engineer";
		staffName= "Raghu";
		salary=80000;
		nativity= "Kop";
		email= "raghu73@gmail.com";
		mobileNo=8765768675;
		Staff.staffInfo(type,staffName,salary,nativity,email,mobileNo);
		type= "Frontend Developer";
		staffName= "Madhan";
		salary=87834;
		nativity= "Odisha";
		email= "raaghu73@gmail.com";
		mobileNo=8765768677;
		Staff.staffInfo(type,staffName,salary,nativity,email,mobileNo);
		type= "Backend Developer";
		staffName= "Aishwarya";
		salary=56669;
		nativity= "Shivmoga";
		email= "Aush32@gmail.com";
		mobileNo=8765768689;
		Staff.staffInfo(type,staffName,salary,nativity,email,mobileNo);
		type= "FullStack Devloper";
		staffName= "Ankithaa";
		salary=76888;
		nativity= "Hodigere";
		email= "anku77@gmail.com";
		 mobileNo=8765768867;
		Staff.staffInfo(type,staffName,salary,nativity,email,mobileNo);
		type= "System Engineer";
		staffName= "Rakshitha";
		salary=546564;
		nativity= "Hodigeree";
		email= "raksh43@gmail.com";
		mobileNo=8765768978;
		Staff.staffInfo(type,staffName,salary,nativity,email,mobileNo);
		type= "Network Engineer";
		staffName= "Ananya";
		salary=878686;
		nativity= "Benkikere";
		email= "anu@gmail.com";
		mobileNo=8765768768;
		Staff.staffInfo(type,staffName,salary,nativity,email,mobileNo);
		type= "CyberSecurity Engineer";
		staffName= "Radhika";
		salary=86768;
		nativity= "Harihar";
		email= "radhika53@gmail.com";
		mobileNo=8765768434;
		Staff.staffInfo(type,staffName,salary,nativity,email,mobileNo);
		type= "Database Administrator";
		staffName= "Vanitha";
		salary=888868;
		nativity= "Challakere";
		email= "vanitha53@gmail.com";
		mobileNo=876576765;
		Staff.staffInfo(type,staffName,salary,nativity,email,mobileNo);
		type= "IT Support Technician ";
		staffName= "Keerthana";
		salary=979897;
		nativity= "Challakeree";
		email= "kerrtha@gmail.com";
		mobileNo=8715768670;
		Staff.staffInfo(type,staffName,salary,nativity,email,mobileNo);
		type= "Cloud Architech";
		staffName= "Sanjana";
		salary=757573;
		nativity= "Channnagiri";
		email= "sanju43@gmail.com";
		mobileNo=8765718680;
		Staff.staffInfo(type,staffName,salary,nativity,email,mobileNo);
		type= "UX/UI Designer";
		staffName= "Prathibha";
		salary=84585;
		nativity= "Billahhi";
		email= "prathi4@gmail.com";
		mobileNo=8765768672;
		Staff.staffInfo(type,staffName,salary,nativity,email,mobileNo);
		type= "Quality Assurance Tester";
		staffName= "Varun";
		salary=766576;
		nativity= "Shivagange";
		email= "varu4@gmail.com";
		mobileNo=8765768643;
		Staff.staffInfo(type,staffName,salary,nativity,email,mobileNo);
		type= "DevOps Engineer";
		staffName= "Prajju";
		salary=76857;
		nativity= "Hiriyur";
		email= "praju74@gmail.com";
		mobileNo=8765768432;
		Staff.staffInfo(type,staffName,salary,nativity,email,mobileNo);
		type= "Data Scietist";
		staffName="Karthik";
		salary=854858;
		nativity= "Bidikere";
		email= "karthik5@gmail.com";
		mobileNo=8765768675;
		Staff.staffInfo(type,staffName,salary,nativity,email,mobileNo);
		String type= "School Principal";
		String staffName= "Balaji";
		int salary=60000;
		String nativity= "Shivmoga";
		String email= "balaji12@gmail.com";
		int mobileNo=9845580918;
		Staff.staffInfo(type,staffName,salary,nativity,email,mobileNo);
		type= "Vice Principal";
		staffName= "Umesh M N";
		salary=50000;
		nativity= "Kaknur";
		email= "umesh123@gmail.com";
		mobileNo=9876567876;
		Staff.staffInfo(type,staffName,salary,nativity,email,mobileNo);
		type= "Dean";
		staffName= "Lakshman";
		salary=12000;
		nativity= "Bangalore";
		email= "lakshman43@gmail.com";
		mobileNo=9865787456;
		Staff.staffInfo(type,staffName,salary,nativity,email,mobileNo);
		type= "Professor";
		staffName= "Shridar";
		salary=9000;
		nativity= "hodigere";
		email= "shridar56@gmail.com";
		mobileNo=9865746545;
		Staff.staffInfo(type,staffName,salary,nativity,email,mobileNo);
		type= "Lecture";
		staffName= "Maruthi";
		salary=15000;
		nativity= "Pavagada";
		email= "maruthi23@gmai.com";
		mobileNo=7665456381;
		Staff.staffInfo(type,staffName,salary,nativity,email,mobileNo);
		type= "Teching Assistant";
		String staffName= "Shivu Kumar";
		salary=80000;
		nativity= "Channagri";
		email= "Shivu43@gmail.com";
		mobileNo=9865453532;
		Staff.staffInfo(type,staffName,salary,nativity,email,mobileNo);
		type= "School Counselor";
		staffName= "Rajesh";
		salary=17000;
		nativity= "Channagiri";
		email= "";
		mobileNo=71726546763;
		Staff.staffInfo(type,staffName,salary,nativity,email,mobileNo);
		type= "Librarian";
		staffName= "Ganesh";
		salary=20000;
		nativity= "Bangalore";
		email= "ganesh91@gmail.com";
		mobileNo=9845590461;
		Staff.staffInfo(type,staffName,salary,nativity,email,mobileNo);
		type= "Rehistrar";
		staffName= "Shambulinga";
		salary=60000;
		nativity= "Kalburgi";
		email= "Shambu76@gmail.com";
		mobileNo=7864657464;
		Staff.staffInfo(type,staffName,salary,nativity,email,mobileNo);
		type= "Admissions Officer";
		staffName= "Prasanna";
		salary=150000;
		nativity= "Hodigere";
		email= "prasanna45@gmail.com";
		mobileNo=6362724663;
		Staff.staffInfo(type,staffName,salary,nativity,email,mobileNo);
		type= "Special Education Teacher";
		staffName= "Kumar";
		salary=50000;
		nativity= "Chitradurga";
		email= "kumar12@gmail.com";
		mobileNo=9845590873;
		Staff.staffInfo(type,staffName,salary,nativity,email,mobileNo);
		type= "Substitute Teacher";
		staffName= "Subhash";
		salary=70000;
		nativity= "Karvar";
		email= "subhash65@gmiail.com";
		mobileNo=9876467464;
		Staff.staffInfo(type,staffName,salary,nativity,email,mobileNo);
		type= "ESL Instuctor";
		staffName= "Pratham";
		salary=35000;
		nativity= "channai";
		email= "prathu36@gmail.com";
		mobileNo=4362636345;
		Staff.staffInfo(type,staffName,salary,nativity,email,mobileNo);
		type= "Lab Assistant";
		staffName= "Paramesh";
		salary=70000;
		nativity= "Holalkere";
		email= "param3453@gmail.com";
		mobileNo=9845590398;
		Staff.staffInfo(type,staffName,salary,nativity,email,mobileNo);
		type= "Career Coach";
		staffName= "Siddesh";
		salary=23000;
		nativity= "Belagam";
		email= "siddu35@gmail.com";
		mobileNo=9874648698;
		Staff.staffInfo(type,staffName,salary,nativity,email,mobileNo);
		type= "Janitor";
		staffName= "Kiran ";
		salary=87000;
		nativity= "Bijapur";
		email= "kiran89@gmail.com";
		mobileNo=7564647448;
		Staff.staffInfo(type,staffName,salary,nativity,email,mobileNo);
		type= "Bus Driver";
		staffName= "Nagaprajwal";
		salary=100000;
		nativity= "Hiriyur";
		email= "naga54@gmail.com";
		mobileNo=7564645354;
		Staff.staffInfo(type,staffName,salary,nativity,email,mobileNo);
		type= "Cafeteria";
		staffName= "Harish";
		salary=7665655469;
		nativity= "Tumkur";
		email= "harish5@gmail.com";
		mobileNo=9878988754;
		Staff.staffInfo(type,staffName,salary,nativity,email,mobileNo);
		type= "Security Guard";
		staffName= "Sudeep";
		salary=89000;
		nativity= "Bijapur";
		email= "sudi43@gmail.com";
		mobileNo=9807667598;
		Staff.staffInfo(type,staffName,salary,nativity,email,mobileNo);
		type= "Student Advisor";
		staffName= "Vishwa";
		salary=45000;
		nativity= "Kerala";
		email= "vishw989@gmail.com";
		mobileNo=8776564653;
		Staff.staffInfo(type,staffName,salary,nativity,email,mobileNo);
		type= "Software Engineer";
		staffName= "Raghu";
		salary=80000;
		nativity= "Kop";
		email= "raghu73@gmail.com";
		mobileNo=8765768675;
		Staff.staffInfo(type,staffName,salary,nativity,email,mobileNo);
		type= "Frontend Developer";
		staffName= "Madhan";
		salary=87834;
		nativity= "Odisha";
		email= "raaghu73@gmail.com";
		mobileNo=8765768677;
		Staff.staffInfo(type,staffName,salary,nativity,email,mobileNo);
		type= "Backend Developer";
		staffName= "Aishwarya";
		salary=56669;
		nativity= "Shivmoga";
		email= "Aush32@gmail.com";
		mobileNo=8765768689;
		Staff.staffInfo(type,staffName,salary,nativity,email,mobileNo);
		type= "FullStack Devloper";
		staffName= "Ankithaa";
		salary=76888;
		nativity= "Hodigere";
		email= "anku77@gmail.com";
		 mobileNo=8765768867;
		Staff.staffInfo(type,staffName,salary,nativity,email,mobileNo);
		type= "System Engineer";
		staffName= "Rakshitha";
		salary=546564;
		nativity= "Hodigeree";
		email= "raksh43@gmail.com";
		mobileNo=8765768978;
		Staff.staffInfo(type,staffName,salary,nativity,email,mobileNo);
		type= "Network Engineer";
		staffName= "Ananya";
		salary=878686;
		nativity= "Benkikere";
		email= "anu@gmail.com";
		mobileNo=8765768768;
		Staff.staffInfo(type,staffName,salary,nativity,email,mobileNo);
		type= "CyberSecurity Engineer";
		staffName= "Radhika";
		salary=86768;
		nativity= "Harihar";
		email= "radhika53@gmail.com";
		mobileNo=8765768434;
		Staff.staffInfo(type,staffName,salary,nativity,email,mobileNo);
		type= "Database Administrator";
		staffName= "Vanitha";
		salary=888868;
		nativity= "Challakere";
		email= "vanitha53@gmail.com";
		mobileNo=876576765;
		Staff.staffInfo(type,staffName,salary,nativity,email,mobileNo);
		type= "IT Support Technician ";
		staffName= "Keerthana";
		salary=979897;
		nativity= "Challakeree";
		email= "kerrtha@gmail.com";
		mobileNo=8765768670;
		Staff.staffInfo(type,staffName,salary,nativity,email,mobileNo);
		type= "Cloud Architech";
		staffName= "Sanjana";
		salary=857573;
		nativity= "Channnagiri";
		email= "sanju43@gmail.com";
		mobileNo=8765768680;
		Staff.staffInfo(type,staffName,salary,nativity,email,mobileNo);
		type= "UX/UI Designer";
		staffName= "Prathibha";
		salary=84585;
		nativity= "Billahhi";
		email= "prathi4@gmail.com";
		mobileNo=8765768672;
		Staff.staffInfo(type,staffName,salary,nativity,email,mobileNo);
		type= "Quality Assurance Tester";
		staffName= "Varun";
		salary=766576;
		nativity= "Shivagange";
		email= "varu4@gmail.com";
		mobileNo=8765768643;
		Staff.staffInfo(type,staffName,salary,nativity,email,mobileNo);
		type= "DevOps Engineer";
		staffName= "Prajju";
		salary=76857;
		nativity= "Hiriyur";
		email= "praju74@gmail.com";
		mobileNo=8765768432;
		Staff.staffInfo(type,staffName,salary,nativity,email,mobileNo);
		type= "Data Scietist";
		staffName="Karthik";
		salary=854858;
		nativity= "Bidikere";
		email= "karthik5@gmail.com";
		mobileNo=8765768675;
		Staff.staffInfo(type,staffName,salary,nativity,email,mobileNo);
		String type= "School Principal";
		String staffName= "Balaji";
		int salary=60000;
		String nativity= "Shivmoga";
		String email= "balaji12@gmail.com";
		int mobileNo=9845580918;
		Staff.staffInfo(type,staffName,salary,nativity,email,mobileNo);
		type= "Vice Principal";
		staffName= "Umesh M N";
		salary=50000;
		nativity= "Kaknur";
		email= "umesh123@gmail.com";
		mobileNo=9876567876;
		Staff.staffInfo(type,staffName,salary,nativity,email,mobileNo);
		type= "Dean";
		staffName= "Lakshman";
		salary=12000;
		nativity= "Bangalore";
		email= "lakshman43@gmail.com";
		mobileNo=9865787456;
		Staff.staffInfo(type,staffName,salary,nativity,email,mobileNo);
		type= "Professor";
		staffName= "Shridar";
		salary=9000;
		nativity= "hodigere";
		email= "shridar56@gmail.com";
		mobileNo=9865746545;
		Staff.staffInfo(type,staffName,salary,nativity,email,mobileNo);
		type= "Lecture";
		staffName= "Maruthi";
		salary=15000;
		nativity= "Pavagada";
		email= "maruthi23@gmai.com";
		mobileNo=7665456381;
		Staff.staffInfo(type,staffName,salary,nativity,email,mobileNo);
		type= "Teching Assistant";
		String staffName= "Shivu Kumar";
		salary=80000;
		nativity= "Channagri";
		email= "Shivu43@gmail.com";
		mobileNo=9865453532;
		Staff.staffInfo(type,staffName,salary,nativity,email,mobileNo);
		type= "School Counselor";
		staffName= "Rajesh";
		salary=17000;
		nativity= "Channagiri";
		email= "";
		mobileNo=71726546763;
		Staff.staffInfo(type,staffName,salary,nativity,email,mobileNo);
		type= "Librarian";
		staffName= "Ganesh";
		salary=20000;
		nativity= "Bangalore";
		email= "ganesh91@gmail.com";
		mobileNo=9845590461;
		Staff.staffInfo(type,staffName,salary,nativity,email,mobileNo);
		type= "Rehistrar";
		staffName= "Shambulinga";
		salary=60000;
		nativity= "Kalburgi";
		email= "Shambu76@gmail.com";
		mobileNo=7864657464;
		Staff.staffInfo(type,staffName,salary,nativity,email,mobileNo);
		type= "Admissions Officer";
		staffName= "Prasanna";
		salary=150000;
		nativity= "Hodigere";
		email= "prasanna45@gmail.com";
		mobileNo=6362724663;
		Staff.staffInfo(type,staffName,salary,nativity,email,mobileNo);
		type= "Special Education Teacher";
		staffName= "Kumar";
		salary=50000;
		nativity= "Chitradurga";
		email= "kumar12@gmail.com";
		mobileNo=9845590873;
		Staff.staffInfo(type,staffName,salary,nativity,email,mobileNo);
		type= "Substitute Teacher";
		staffName= "Subhash";
		salary=70000;
		nativity= "Karvar";
		email= "subhash65@gmiail.com";
		mobileNo=9876467464;
		Staff.staffInfo(type,staffName,salary,nativity,email,mobileNo);
		type= "ESL Instuctor";
		staffName= "Pratham";
		salary=35000;
		nativity= "channai";
		email= "prathu36@gmail.com";
		mobileNo=4362636345;
		Staff.staffInfo(type,staffName,salary,nativity,email,mobileNo);
		type= "Lab Assistant";
		staffName= "Paramesh";
		salary=70000;
		nativity= "Holalkere";
		email= "param3453@gmail.com";
		mobileNo=9845590398;
		Staff.staffInfo(type,staffName,salary,nativity,email,mobileNo);
		type= "Career Coach";
		staffName= "Siddesh";
		salary=23000;
		nativity= "Belagam";
		email= "siddu35@gmail.com";
		mobileNo=9874648698;
		Staff.staffInfo(type,staffName,salary,nativity,email,mobileNo);
		type= "Janitor";
		staffName= "Kiran ";
		salary=87000;
		nativity= "Bijapur";
		email= "kiran89@gmail.com";
		mobileNo=7564647448;
		Staff.staffInfo(type,staffName,salary,nativity,email,mobileNo);
		type= "Bus Driver";
		staffName= "Nagaprajwal";
		salary=100000;
		nativity= "Hiriyur";
		email= "naga54@gmail.com";
		mobileNo=7564645354;
		Staff.staffInfo(type,staffName,salary,nativity,email,mobileNo);
		type= "Cafeteria";
		staffName= "Harish";
		salary=7665655469;
		nativity= "Tumkur";
		email= "harish5@gmail.com";
		mobileNo=9878988754;
		Staff.staffInfo(type,staffName,salary,nativity,email,mobileNo);
		type= "Security Guard";
		staffName= "Sudeep";
		salary=89000;
		nativity= "Bijapur";
		email= "sudi43@gmail.com";
		mobileNo=9807667598;
		Staff.staffInfo(type,staffName,salary,nativity,email,mobileNo);
		type= "Student Advisor";
		staffName= "Vishwa";
		salary=45000;
		nativity= "Kerala";
		email= "vishw989@gmail.com";
		mobileNo=8776564653;
		Staff.staffInfo(type,staffName,salary,nativity,email,mobileNo);
		type= "Software Engineer";
		staffName= "Raghu";
		salary=80000;
		nativity= "Kop";
		email= "raghu73@gmail.com";
		mobileNo=8765768675;
		Staff.staffInfo(type,staffName,salary,nativity,email,mobileNo);
		type= "Frontend Developer";
		staffName= "Madhan";
		salary=8783i4;
		nativity= "Odisha";
		email= "raaguhu73@gmail.com";
		mobileNo=8768768677;
		Staff.staffInfo(type,staffName,salary,nativity,email,mobileNo);
		type= "Backend Developer";
		staffName= "Aiishwarya";
		salary=56661;
		nativity= "Shiivmoga";
		email= "Aush372@gmail.com";
		mobileNo=8765668689;
		Staff.staffInfo(type,staffName,salary,nativity,email,mobileNo);
		type= "FullStack Devloper";
		staffName= "Anskithaa";
		salary=76848;
		nativity= "Hodigere";
		email= "anku77@gmail.com";
		 mobileNo=8767768867;
		Staff.staffInfo(type,staffName,salary,nativity,email,mobileNo);
		type= "System Engineer";
		staffName= "Rakshitha";
		salary=5465648;
		nativity= "Hodirgeree";
		email= "raksh436@gmail.com";
		mobileNo=8765760978;
		Staff.staffInfo(type,staffName,salary,nativity,email,mobileNo);
		type= "Network Engineer";
		staffName= "Anannya";
		salary=8786866;
		nativity= "Bjenkikere";
		email= "anhu@gmail.com";
		mobileNo=875768768;
		Staff.staffInfo(type,staffName,salary,nativity,email,mobileNo);
		type= "CyberSecurity Engineer";
		staffName= "Raadhika";
		salary=867688;
		nativity= "Hairhar";
		email= "radhika53@gmail.com";
		mobileNo=8795968434;
		Staff.staffInfo(type,staffName,salary,nativity,email,mobileNo);
		type= "Database Administrator";
		staffName= "Vaanitha";
		salary=88888;
		nativity= "Callakere";
		email= "vaitha53@gmail.com";
		mobileNo=879576765;
		Staff.staffInfo(type,staffName,salary,nativity,email,mobileNo);
		type= "IT Support Technician ";
		staffName= "Kerthana";
		salary=97989;
		nativity= "Challakree";
		email= "kertha@gmail.com";
		mobileNo=876568670;
		Staff.staffInfo(type,staffName,salary,nativity,email,mobileNo);
		type= "Cloud Architech";
		staffName= "Saanjana";
		salary=857593;
		nativity= "Channnagiri";
		email= "sanjju43@gmail.com";
		mobileNo=8765798680;
		Staff.staffInfo(type,staffName,salary,nativity,email,mobileNo);
		type= "UX/UI Designer";
		staffName= "Praathibha";
		salary=8485;
		nativity= "Billahhi";
		email= "praathi4@gmail.com";
		mobileNo=865768672;
		Staff.staffInfo(type,staffName,salary,nativity,email,mobileNo);
		type= "Qality Assurance Tester";
		staffName= "Varun";
		salary=76876;
		nativity= "Shivagange";
		email= "vara4@gmail.com";
		mobileNo=8765868643;
		Staff.staffInfo(type,staffName,salary,nativity,email,mobileNo);
		type= "DevOps Engineer";
		staffName= "Praajju";
		salary=76887;
		nativity= "Hiriyur";
		email= "prajju74@gmail.com";
		mobileNo=8768768432;
		Staff.staffInfo(type,staffName,salary,nativity,email,mobileNo);
		type= "Data Scietist";
		staffName="Kaarthik";
		salary=854859;
		nativity= "Bidkere";
		email= "karthi5@gmail.com";
		mobileNo=8765766675;
		Staff.staffInfo(type,staffName,salary,nativity,email,mobileNo);
		type= "Librarian";
		staffName= "Ganesh";
		salary=20000;
		nativity= "Bangalore";
		email= "ganesh91@gmail.com";
		mobileNo=9845590461;
		Staff.staffInfo(type,staffName,salary,nativity,email,mobileNo);
		type= "Rehistrar";
		staffName= "Shambulinga";
		salary=60000;
		nativity= "Kalburgi";
		email= "Shambu76@gmail.com";
		mobileNo=7864657464;
		Staff.staffInfo(type,staffName,salary,nativity,email,mobileNo);
		type= "Admissions Officer";
		staffName= "Prasanna";
		salary=150000;
		nativity= "Hodigere";
		email= "prasanna45@gmail.com";
		mobileNo=6362724663;
		Staff.staffInfo(type,staffName,salary,nativity,email,mobileNo);
		type= "Special Education Teacher";
		staffName= "Kumar";
		salary=50000;
		nativity= "Chitradurga";
		email= "kumar12@gmail.com";
		mobileNo=9845590873;
		Staff.staffInfo(type,staffName,salary,nativity,email,mobileNo);
		type= "Substitute Teacher";
		staffName= "Subhash";
		salary=70000;
		nativity= "Karvar";
		email= "subhash65@gmiail.com";
		mobileNo=9876467464;
		Staff.staffInfo(type,staffName,salary,nativity,email,mobileNo);
		type= "ESL Instuctor";
		staffName= "Pratham";
		salary=35000;
		nativity= "channai";
		email= "prathu36@gmail.com";
		mobileNo=4362636345;
		Staff.staffInfo(type,staffName,salary,nativity,email,mobileNo);
		type= "Lab Assistant";
		staffName= "Paramesh";
		salary=70000;
		nativity= "Holalkere";
		email= "param3453@gmail.com";
		mobileNo=9845590398;
		Staff.staffInfo(type,staffName,salary,nativity,email,mobileNo);
		type= "Career Coach";
		staffName= "Siddesh";
		salary=23000;
		nativity= "Belagam";
		email= "siddu35@gmail.com";
		mobileNo=9874648698;
		Staff.staffInfo(type,staffName,salary,nativity,email,mobileNo);
		type= "Janitor";
		staffName= "Kiran ";
		salary=87000;
		nativity= "Bijapur";
		email= "kiran89@gmail.com";
		mobileNo=7564647448;
		Staff.staffInfo(type,staffName,salary,nativity,email,mobileNo);
		type= "Bus Driver";
		staffName= "Nagaprajwal";
		salary=100000;
		nativity= "Hiriyur";
		email= "naga54@gmail.com";
		mobileNo=7564645354;
		Staff.staffInfo(type,staffName,salary,nativity,email,mobileNo);
		type= "Cafeteria";
		staffName= "Harish";
		salary=7665655469;
		nativity= "Tumkur";
		email= "harish5@gmail.com";
		mobileNo=9878988754;
		Staff.staffInfo(type,staffName,salary,nativity,email,mobileNo);
		type= "Security Guard";
		staffName= "Sudeep";
		salary=89000;
		nativity= "Bijapur";
		email= "sudi43@gmail.com";
		mobileNo=9807667598;
		Staff.staffInfo(type,staffName,salary,nativity,email,mobileNo);
		type= "Student Advisor";
		staffName= "Vishwa";
		salary=45000;
		nativity= "Kerala";
		email= "vishw989@gmail.com";
		mobileNo=8776564653;
		Staff.staffInfo(type,staffName,salary,nativity,email,mobileNo);
		type= "Software Engineer";
		staffName= "Raghu";
		salary=80000;
		nativity= "Kop";
		email= "raghu73@gmail.com";
		mobileNo=8765768675;
		Staff.staffInfo(type,staffName,salary,nativity,email,mobileNo);
		type= "Frontend Developer";
		staffName= "Madhan";
		salary=87834;
		nativity= "Odisha";
		email= "raaghu73@gmail.com";
		mobileNo=8765768677;
		Staff.staffInfo(type,staffName,salary,nativity,email,mobileNo);
		type= "Backend Developer";
		staffName= "Aishwarya";
		salary=56669;
		nativity= "Shivmoga";
		email= "Aush32@gmail.com";
		mobileNo=8765768689;
		Staff.staffInfo(type,staffName,salary,nativity,email,mobileNo);
		type= "Librarian";
		staffName= "Ganesh";
		salary=20000;
		nativity= "Bangalore";
		email= "ganesh91@gmail.com";
		mobileNo=9845590461;
		Staff.staffInfo(type,staffName,salary,nativity,email,mobileNo);
		type= "Rehistrar";
		staffName= "Shambulinga";
		salary=60000;
		nativity= "Kalburgi";
		email= "Shambu76@gmail.com";
		mobileNo=7864657464;
		Staff.staffInfo(type,staffName,salary,nativity,email,mobileNo);
		type= "Admissions Officer";
		staffName= "Prasanna";
		salary=150000;
		nativity= "Hodigere";
		email= "prasanna45@gmail.com";
		mobileNo=6362724663;
		Staff.staffInfo(type,staffName,salary,nativity,email,mobileNo);
		type= "Special Education Teacher";
		staffName= "Kumar";
		salary=50000;
		nativity= "Chitradurga";
		email= "kumar12@gmail.com";
		mobileNo=9845590873;
		Staff.staffInfo(type,staffName,salary,nativity,email,mobileNo);
		type= "Substitute Teacher";
		staffName= "Subhash";
		salary=70000;
		nativity= "Karvar";
		email= "subhash65@gmiail.com";
		mobileNo=9876467464;
		Staff.staffInfo(type,staffName,salary,nativity,email,mobileNo);
		type= "ESL Instuctor";
		staffName= "Pratham";
		salary=35000;
		nativity= "channai";
		email= "prathu36@gmail.com";
		mobileNo=4362636345;
		Staff.staffInfo(type,staffName,salary,nativity,email,mobileNo);
		type= "Lab Assistant";
		staffName= "Paramesh";
		salary=70000;
		nativity= "Holalkere";
		email= "param3453@gmail.com";
		mobileNo=9845590398;
		Staff.staffInfo(type,staffName,salary,nativity,email,mobileNo);
		type= "Career Coach";
		staffName= "Siddesh";
		salary=23000;
		nativity= "Belagam";
		email= "siddu35@gmail.com";
		mobileNo=9874648698;
		Staff.staffInfo(type,staffName,salary,nativity,email,mobileNo);
		type= "Janitor";
		staffName= "Kiran ";
		salary=87000;
		nativity= "Bijapur";
		email= "kiran89@gmail.com";
		mobileNo=7564647448;
		Staff.staffInfo(type,staffName,salary,nativity,email,mobileNo);
		type= "Bus Driver";
		staffName= "Nagaprajwal";
		salary=100000;
		nativity= "Hiriyur";
		email= "naga54@gmail.com";
		mobileNo=7564645354;
		Staff.staffInfo(type,staffName,salary,nativity,email,mobileNo);
		type= "Cafeteria";
		staffName= "Harish";
		salary=7665655469;
		nativity= "Tumkur";
		email= "harish5@gmail.com";
		mobileNo=9878988754;
		Staff.staffInfo(type,staffName,salary,nativity,email,mobileNo);
		type= "Security Guard";
		staffName= "Sudeep";
		salary=89000;
		nativity= "Bijapur";
		email= "sudi43@gmail.com";
		mobileNo=9807667598;
		Staff.staffInfo(type,staffName,salary,nativity,email,mobileNo);
		type= "Student Advisor";
		staffName= "Vishwa";
		salary=45000;
		nativity= "Kerala";
		email= "vishw989@gmail.com";
		mobileNo=8776564653;
		Staff.staffInfo(type,staffName,salary,nativity,email,mobileNo);
		type= "Software Engineer";
		staffName= "Raghu";
		salary=80000;
		nativity= "Kop";
		email= "raghu73@gmail.com";
		mobileNo=8765768675;
		Staff.staffInfo(type,staffName,salary,nativity,email,mobileNo);
		
		type= "Frontend Developer";
		staffName= "Madhan";
		salary=87834;
		nativity= "Odisha";
		email= "raaghu73@gmail.com";
		mobileNo=8765768677;
		Staff.staffInfo(type,staffName,salary,nativity,email,mobileNo);
		
		type= "Backend Developer";
		staffName= "Aishwarya";
		salary=56669;
		nativity= "Shivmoga";
		email= "Aush32@gmail.com";
		mobileNo=8765768689;
		Staff.staffInfo(type,staffName,salary,nativity,email,mobileNo);	
		
	}
}